// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportmessage"
	"github.com/Wei-Shaw/sub2api/ent/supportthread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportThreadUpdate is the builder for updating SupportThread entities.
type SupportThreadUpdate struct {
	config
	hooks    []Hook
	mutation *SupportThreadMutation
}

// Where appends a list predicates to the SupportThreadUpdate builder.
func (_u *SupportThreadUpdate) Where(ps ...predicate.SupportThread) *SupportThreadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportThreadUpdate) SetUpdatedAt(v time.Time) *SupportThreadUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SupportThreadUpdate) SetUserID(v int64) *SupportThreadUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableUserID(v *int64) *SupportThreadUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *SupportThreadUpdate) SetSubject(v string) *SupportThreadUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableSubject(v *string) *SupportThreadUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportThreadUpdate) SetStatus(v string) *SupportThreadUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableStatus(v *string) *SupportThreadUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SupportThreadUpdate) SetPriority(v string) *SupportThreadUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillablePriority(v *string) *SupportThreadUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *SupportThreadUpdate) SetType(v string) *SupportThreadUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableType(v *string) *SupportThreadUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (_u *SupportThreadUpdate) SetAssignedAdminID(v int64) *SupportThreadUpdate {
	_u.mutation.SetAssignedAdminID(v)
	return _u
}

// SetNillableAssignedAdminID sets the "assigned_admin_id" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableAssignedAdminID(v *int64) *SupportThreadUpdate {
	if v != nil {
		_u.SetAssignedAdminID(*v)
	}
	return _u
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (_u *SupportThreadUpdate) ClearAssignedAdminID() *SupportThreadUpdate {
	_u.mutation.ClearAssignedAdminID()
	return _u
}

// SetLastMessageID sets the "last_message_id" field.
func (_u *SupportThreadUpdate) SetLastMessageID(v int64) *SupportThreadUpdate {
	_u.mutation.ResetLastMessageID()
	_u.mutation.SetLastMessageID(v)
	return _u
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableLastMessageID(v *int64) *SupportThreadUpdate {
	if v != nil {
		_u.SetLastMessageID(*v)
	}
	return _u
}

// AddLastMessageID adds value to the "last_message_id" field.
func (_u *SupportThreadUpdate) AddLastMessageID(v int64) *SupportThreadUpdate {
	_u.mutation.AddLastMessageID(v)
	return _u
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (_u *SupportThreadUpdate) ClearLastMessageID() *SupportThreadUpdate {
	_u.mutation.ClearLastMessageID()
	return _u
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (_u *SupportThreadUpdate) SetLastMessageSenderType(v string) *SupportThreadUpdate {
	_u.mutation.SetLastMessageSenderType(v)
	return _u
}

// SetNillableLastMessageSenderType sets the "last_message_sender_type" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableLastMessageSenderType(v *string) *SupportThreadUpdate {
	if v != nil {
		_u.SetLastMessageSenderType(*v)
	}
	return _u
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (_u *SupportThreadUpdate) SetLastMessageExcerpt(v string) *SupportThreadUpdate {
	_u.mutation.SetLastMessageExcerpt(v)
	return _u
}

// SetNillableLastMessageExcerpt sets the "last_message_excerpt" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableLastMessageExcerpt(v *string) *SupportThreadUpdate {
	if v != nil {
		_u.SetLastMessageExcerpt(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *SupportThreadUpdate) SetLastMessageAt(v time.Time) *SupportThreadUpdate {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableLastMessageAt(v *time.Time) *SupportThreadUpdate {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (_u *SupportThreadUpdate) SetUserLastReadMessageID(v int64) *SupportThreadUpdate {
	_u.mutation.ResetUserLastReadMessageID()
	_u.mutation.SetUserLastReadMessageID(v)
	return _u
}

// SetNillableUserLastReadMessageID sets the "user_last_read_message_id" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableUserLastReadMessageID(v *int64) *SupportThreadUpdate {
	if v != nil {
		_u.SetUserLastReadMessageID(*v)
	}
	return _u
}

// AddUserLastReadMessageID adds value to the "user_last_read_message_id" field.
func (_u *SupportThreadUpdate) AddUserLastReadMessageID(v int64) *SupportThreadUpdate {
	_u.mutation.AddUserLastReadMessageID(v)
	return _u
}

// ClearUserLastReadMessageID clears the value of the "user_last_read_message_id" field.
func (_u *SupportThreadUpdate) ClearUserLastReadMessageID() *SupportThreadUpdate {
	_u.mutation.ClearUserLastReadMessageID()
	return _u
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (_u *SupportThreadUpdate) SetUserLastReadAt(v time.Time) *SupportThreadUpdate {
	_u.mutation.SetUserLastReadAt(v)
	return _u
}

// SetNillableUserLastReadAt sets the "user_last_read_at" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableUserLastReadAt(v *time.Time) *SupportThreadUpdate {
	if v != nil {
		_u.SetUserLastReadAt(*v)
	}
	return _u
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (_u *SupportThreadUpdate) ClearUserLastReadAt() *SupportThreadUpdate {
	_u.mutation.ClearUserLastReadAt()
	return _u
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (_u *SupportThreadUpdate) SetAdminLastReadMessageID(v int64) *SupportThreadUpdate {
	_u.mutation.ResetAdminLastReadMessageID()
	_u.mutation.SetAdminLastReadMessageID(v)
	return _u
}

// SetNillableAdminLastReadMessageID sets the "admin_last_read_message_id" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableAdminLastReadMessageID(v *int64) *SupportThreadUpdate {
	if v != nil {
		_u.SetAdminLastReadMessageID(*v)
	}
	return _u
}

// AddAdminLastReadMessageID adds value to the "admin_last_read_message_id" field.
func (_u *SupportThreadUpdate) AddAdminLastReadMessageID(v int64) *SupportThreadUpdate {
	_u.mutation.AddAdminLastReadMessageID(v)
	return _u
}

// ClearAdminLastReadMessageID clears the value of the "admin_last_read_message_id" field.
func (_u *SupportThreadUpdate) ClearAdminLastReadMessageID() *SupportThreadUpdate {
	_u.mutation.ClearAdminLastReadMessageID()
	return _u
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (_u *SupportThreadUpdate) SetAdminLastReadAt(v time.Time) *SupportThreadUpdate {
	_u.mutation.SetAdminLastReadAt(v)
	return _u
}

// SetNillableAdminLastReadAt sets the "admin_last_read_at" field if the given value is not nil.
func (_u *SupportThreadUpdate) SetNillableAdminLastReadAt(v *time.Time) *SupportThreadUpdate {
	if v != nil {
		_u.SetAdminLastReadAt(*v)
	}
	return _u
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (_u *SupportThreadUpdate) ClearAdminLastReadAt() *SupportThreadUpdate {
	_u.mutation.ClearAdminLastReadAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SupportThreadUpdate) SetUser(v *User) *SupportThreadUpdate {
	return _u.SetUserID(v.ID)
}

// SetAssignedAdmin sets the "assigned_admin" edge to the User entity.
func (_u *SupportThreadUpdate) SetAssignedAdmin(v *User) *SupportThreadUpdate {
	return _u.SetAssignedAdminID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the SupportMessage entity by IDs.
func (_u *SupportThreadUpdate) AddMessageIDs(ids ...int64) *SupportThreadUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the SupportMessage entity.
func (_u *SupportThreadUpdate) AddMessages(v ...*SupportMessage) *SupportThreadUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the SupportThreadMutation object of the builder.
func (_u *SupportThreadUpdate) Mutation() *SupportThreadMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SupportThreadUpdate) ClearUser() *SupportThreadUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAssignedAdmin clears the "assigned_admin" edge to the User entity.
func (_u *SupportThreadUpdate) ClearAssignedAdmin() *SupportThreadUpdate {
	_u.mutation.ClearAssignedAdmin()
	return _u
}

// ClearMessages clears all "messages" edges to the SupportMessage entity.
func (_u *SupportThreadUpdate) ClearMessages() *SupportThreadUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to SupportMessage entities by IDs.
func (_u *SupportThreadUpdate) RemoveMessageIDs(ids ...int64) *SupportThreadUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to SupportMessage entities.
func (_u *SupportThreadUpdate) RemoveMessages(v ...*SupportMessage) *SupportThreadUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportThreadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportThreadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportThreadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportThreadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportThreadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportthread.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportThreadUpdate) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := supportthread.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SupportThread.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportthread.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportThread.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := supportthread.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportThread.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := supportthread.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SupportThread.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMessageSenderType(); ok {
		if err := supportthread.LastMessageSenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "last_message_sender_type", err: fmt.Errorf(`ent: validator failed for field "SupportThread.last_message_sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMessageExcerpt(); ok {
		if err := supportthread.LastMessageExcerptValidator(v); err != nil {
			return &ValidationError{Name: "last_message_excerpt", err: fmt.Errorf(`ent: validator failed for field "SupportThread.last_message_excerpt": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportThread.user"`)
	}
	return nil
}

func (_u *SupportThreadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportthread.Table, supportthread.Columns, sqlgraph.NewFieldSpec(supportthread.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportthread.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(supportthread.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportthread.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(supportthread.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(supportthread.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageID(); ok {
		_spec.SetField(supportthread.FieldLastMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastMessageID(); ok {
		_spec.AddField(supportthread.FieldLastMessageID, field.TypeInt64, value)
	}
	if _u.mutation.LastMessageIDCleared() {
		_spec.ClearField(supportthread.FieldLastMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastMessageSenderType(); ok {
		_spec.SetField(supportthread.FieldLastMessageSenderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageExcerpt(); ok {
		_spec.SetField(supportthread.FieldLastMessageExcerpt, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(supportthread.FieldLastMessageAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserLastReadMessageID(); ok {
		_spec.SetField(supportthread.FieldUserLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserLastReadMessageID(); ok {
		_spec.AddField(supportthread.FieldUserLastReadMessageID, field.TypeInt64, value)
	}
	if _u.mutation.UserLastReadMessageIDCleared() {
		_spec.ClearField(supportthread.FieldUserLastReadMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserLastReadAt(); ok {
		_spec.SetField(supportthread.FieldUserLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.UserLastReadAtCleared() {
		_spec.ClearField(supportthread.FieldUserLastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AdminLastReadMessageID(); ok {
		_spec.SetField(supportthread.FieldAdminLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminLastReadMessageID(); ok {
		_spec.AddField(supportthread.FieldAdminLastReadMessageID, field.TypeInt64, value)
	}
	if _u.mutation.AdminLastReadMessageIDCleared() {
		_spec.ClearField(supportthread.FieldAdminLastReadMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AdminLastReadAt(); ok {
		_spec.SetField(supportthread.FieldAdminLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.AdminLastReadAtCleared() {
		_spec.ClearField(supportthread.FieldAdminLastReadAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportthread.UserTable,
			Columns: []string{supportthread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportthread.UserTable,
			Columns: []string{supportthread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedAdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportthread.AssignedAdminTable,
			Columns: []string{supportthread.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedAdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportthread.AssignedAdminTable,
			Columns: []string{supportthread.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportthread.MessagesTable,
			Columns: []string{supportthread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportthread.MessagesTable,
			Columns: []string{supportthread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportthread.MessagesTable,
			Columns: []string{supportthread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportthread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportThreadUpdateOne is the builder for updating a single SupportThread entity.
type SupportThreadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportThreadMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportThreadUpdateOne) SetUpdatedAt(v time.Time) *SupportThreadUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SupportThreadUpdateOne) SetUserID(v int64) *SupportThreadUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableUserID(v *int64) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *SupportThreadUpdateOne) SetSubject(v string) *SupportThreadUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableSubject(v *string) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportThreadUpdateOne) SetStatus(v string) *SupportThreadUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableStatus(v *string) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SupportThreadUpdateOne) SetPriority(v string) *SupportThreadUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillablePriority(v *string) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *SupportThreadUpdateOne) SetType(v string) *SupportThreadUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableType(v *string) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (_u *SupportThreadUpdateOne) SetAssignedAdminID(v int64) *SupportThreadUpdateOne {
	_u.mutation.SetAssignedAdminID(v)
	return _u
}

// SetNillableAssignedAdminID sets the "assigned_admin_id" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableAssignedAdminID(v *int64) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetAssignedAdminID(*v)
	}
	return _u
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (_u *SupportThreadUpdateOne) ClearAssignedAdminID() *SupportThreadUpdateOne {
	_u.mutation.ClearAssignedAdminID()
	return _u
}

// SetLastMessageID sets the "last_message_id" field.
func (_u *SupportThreadUpdateOne) SetLastMessageID(v int64) *SupportThreadUpdateOne {
	_u.mutation.ResetLastMessageID()
	_u.mutation.SetLastMessageID(v)
	return _u
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableLastMessageID(v *int64) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetLastMessageID(*v)
	}
	return _u
}

// AddLastMessageID adds value to the "last_message_id" field.
func (_u *SupportThreadUpdateOne) AddLastMessageID(v int64) *SupportThreadUpdateOne {
	_u.mutation.AddLastMessageID(v)
	return _u
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (_u *SupportThreadUpdateOne) ClearLastMessageID() *SupportThreadUpdateOne {
	_u.mutation.ClearLastMessageID()
	return _u
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (_u *SupportThreadUpdateOne) SetLastMessageSenderType(v string) *SupportThreadUpdateOne {
	_u.mutation.SetLastMessageSenderType(v)
	return _u
}

// SetNillableLastMessageSenderType sets the "last_message_sender_type" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableLastMessageSenderType(v *string) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetLastMessageSenderType(*v)
	}
	return _u
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (_u *SupportThreadUpdateOne) SetLastMessageExcerpt(v string) *SupportThreadUpdateOne {
	_u.mutation.SetLastMessageExcerpt(v)
	return _u
}

// SetNillableLastMessageExcerpt sets the "last_message_excerpt" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableLastMessageExcerpt(v *string) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetLastMessageExcerpt(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *SupportThreadUpdateOne) SetLastMessageAt(v time.Time) *SupportThreadUpdateOne {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableLastMessageAt(v *time.Time) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (_u *SupportThreadUpdateOne) SetUserLastReadMessageID(v int64) *SupportThreadUpdateOne {
	_u.mutation.ResetUserLastReadMessageID()
	_u.mutation.SetUserLastReadMessageID(v)
	return _u
}

// SetNillableUserLastReadMessageID sets the "user_last_read_message_id" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableUserLastReadMessageID(v *int64) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetUserLastReadMessageID(*v)
	}
	return _u
}

// AddUserLastReadMessageID adds value to the "user_last_read_message_id" field.
func (_u *SupportThreadUpdateOne) AddUserLastReadMessageID(v int64) *SupportThreadUpdateOne {
	_u.mutation.AddUserLastReadMessageID(v)
	return _u
}

// ClearUserLastReadMessageID clears the value of the "user_last_read_message_id" field.
func (_u *SupportThreadUpdateOne) ClearUserLastReadMessageID() *SupportThreadUpdateOne {
	_u.mutation.ClearUserLastReadMessageID()
	return _u
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (_u *SupportThreadUpdateOne) SetUserLastReadAt(v time.Time) *SupportThreadUpdateOne {
	_u.mutation.SetUserLastReadAt(v)
	return _u
}

// SetNillableUserLastReadAt sets the "user_last_read_at" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableUserLastReadAt(v *time.Time) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetUserLastReadAt(*v)
	}
	return _u
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (_u *SupportThreadUpdateOne) ClearUserLastReadAt() *SupportThreadUpdateOne {
	_u.mutation.ClearUserLastReadAt()
	return _u
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (_u *SupportThreadUpdateOne) SetAdminLastReadMessageID(v int64) *SupportThreadUpdateOne {
	_u.mutation.ResetAdminLastReadMessageID()
	_u.mutation.SetAdminLastReadMessageID(v)
	return _u
}

// SetNillableAdminLastReadMessageID sets the "admin_last_read_message_id" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableAdminLastReadMessageID(v *int64) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetAdminLastReadMessageID(*v)
	}
	return _u
}

// AddAdminLastReadMessageID adds value to the "admin_last_read_message_id" field.
func (_u *SupportThreadUpdateOne) AddAdminLastReadMessageID(v int64) *SupportThreadUpdateOne {
	_u.mutation.AddAdminLastReadMessageID(v)
	return _u
}

// ClearAdminLastReadMessageID clears the value of the "admin_last_read_message_id" field.
func (_u *SupportThreadUpdateOne) ClearAdminLastReadMessageID() *SupportThreadUpdateOne {
	_u.mutation.ClearAdminLastReadMessageID()
	return _u
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (_u *SupportThreadUpdateOne) SetAdminLastReadAt(v time.Time) *SupportThreadUpdateOne {
	_u.mutation.SetAdminLastReadAt(v)
	return _u
}

// SetNillableAdminLastReadAt sets the "admin_last_read_at" field if the given value is not nil.
func (_u *SupportThreadUpdateOne) SetNillableAdminLastReadAt(v *time.Time) *SupportThreadUpdateOne {
	if v != nil {
		_u.SetAdminLastReadAt(*v)
	}
	return _u
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (_u *SupportThreadUpdateOne) ClearAdminLastReadAt() *SupportThreadUpdateOne {
	_u.mutation.ClearAdminLastReadAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SupportThreadUpdateOne) SetUser(v *User) *SupportThreadUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAssignedAdmin sets the "assigned_admin" edge to the User entity.
func (_u *SupportThreadUpdateOne) SetAssignedAdmin(v *User) *SupportThreadUpdateOne {
	return _u.SetAssignedAdminID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the SupportMessage entity by IDs.
func (_u *SupportThreadUpdateOne) AddMessageIDs(ids ...int64) *SupportThreadUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the SupportMessage entity.
func (_u *SupportThreadUpdateOne) AddMessages(v ...*SupportMessage) *SupportThreadUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the SupportThreadMutation object of the builder.
func (_u *SupportThreadUpdateOne) Mutation() *SupportThreadMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SupportThreadUpdateOne) ClearUser() *SupportThreadUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAssignedAdmin clears the "assigned_admin" edge to the User entity.
func (_u *SupportThreadUpdateOne) ClearAssignedAdmin() *SupportThreadUpdateOne {
	_u.mutation.ClearAssignedAdmin()
	return _u
}

// ClearMessages clears all "messages" edges to the SupportMessage entity.
func (_u *SupportThreadUpdateOne) ClearMessages() *SupportThreadUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to SupportMessage entities by IDs.
func (_u *SupportThreadUpdateOne) RemoveMessageIDs(ids ...int64) *SupportThreadUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to SupportMessage entities.
func (_u *SupportThreadUpdateOne) RemoveMessages(v ...*SupportMessage) *SupportThreadUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the SupportThreadUpdate builder.
func (_u *SupportThreadUpdateOne) Where(ps ...predicate.SupportThread) *SupportThreadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportThreadUpdateOne) Select(field string, fields ...string) *SupportThreadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportThread entity.
func (_u *SupportThreadUpdateOne) Save(ctx context.Context) (*SupportThread, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportThreadUpdateOne) SaveX(ctx context.Context) *SupportThread {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportThreadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportThreadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportThreadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportthread.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportThreadUpdateOne) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := supportthread.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SupportThread.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportthread.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportThread.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := supportthread.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportThread.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := supportthread.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SupportThread.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMessageSenderType(); ok {
		if err := supportthread.LastMessageSenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "last_message_sender_type", err: fmt.Errorf(`ent: validator failed for field "SupportThread.last_message_sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMessageExcerpt(); ok {
		if err := supportthread.LastMessageExcerptValidator(v); err != nil {
			return &ValidationError{Name: "last_message_excerpt", err: fmt.Errorf(`ent: validator failed for field "SupportThread.last_message_excerpt": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportThread.user"`)
	}
	return nil
}

func (_u *SupportThreadUpdateOne) sqlSave(ctx context.Context) (_node *SupportThread, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportthread.Table, supportthread.Columns, sqlgraph.NewFieldSpec(supportthread.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportThread.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportthread.FieldID)
		for _, f := range fields {
			if !supportthread.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportthread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportthread.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(supportthread.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportthread.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(supportthread.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(supportthread.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageID(); ok {
		_spec.SetField(supportthread.FieldLastMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastMessageID(); ok {
		_spec.AddField(supportthread.FieldLastMessageID, field.TypeInt64, value)
	}
	if _u.mutation.LastMessageIDCleared() {
		_spec.ClearField(supportthread.FieldLastMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastMessageSenderType(); ok {
		_spec.SetField(supportthread.FieldLastMessageSenderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageExcerpt(); ok {
		_spec.SetField(supportthread.FieldLastMessageExcerpt, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(supportthread.FieldLastMessageAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserLastReadMessageID(); ok {
		_spec.SetField(supportthread.FieldUserLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserLastReadMessageID(); ok {
		_spec.AddField(supportthread.FieldUserLastReadMessageID, field.TypeInt64, value)
	}
	if _u.mutation.UserLastReadMessageIDCleared() {
		_spec.ClearField(supportthread.FieldUserLastReadMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserLastReadAt(); ok {
		_spec.SetField(supportthread.FieldUserLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.UserLastReadAtCleared() {
		_spec.ClearField(supportthread.FieldUserLastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AdminLastReadMessageID(); ok {
		_spec.SetField(supportthread.FieldAdminLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminLastReadMessageID(); ok {
		_spec.AddField(supportthread.FieldAdminLastReadMessageID, field.TypeInt64, value)
	}
	if _u.mutation.AdminLastReadMessageIDCleared() {
		_spec.ClearField(supportthread.FieldAdminLastReadMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AdminLastReadAt(); ok {
		_spec.SetField(supportthread.FieldAdminLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.AdminLastReadAtCleared() {
		_spec.ClearField(supportthread.FieldAdminLastReadAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportthread.UserTable,
			Columns: []string{supportthread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportthread.UserTable,
			Columns: []string{supportthread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedAdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportthread.AssignedAdminTable,
			Columns: []string{supportthread.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedAdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportthread.AssignedAdminTable,
			Columns: []string{supportthread.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportthread.MessagesTable,
			Columns: []string{supportthread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportthread.MessagesTable,
			Columns: []string{supportthread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportthread.MessagesTable,
			Columns: []string{supportthread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportThread{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportthread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
