// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/supportmessage"
	"github.com/Wei-Shaw/sub2api/ent/supportthread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportMessage is the model entity for the SupportMessage schema.
type SupportMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 工单服务线程 ID
	ThreadID int64 `json:"thread_id,omitempty"`
	// 发送方: user, admin, system
	SenderType string `json:"sender_type,omitempty"`
	// 发送方用户 ID，系统消息为空
	SenderID *int64 `json:"sender_id,omitempty"`
	// 消息类型: text, notice, operation_log, system_event
	MessageType string `json:"message_type,omitempty"`
	// 内容格式: plain, markdown
	ContentFormat string `json:"content_format,omitempty"`
	// 消息标题，可为空
	Title string `json:"title,omitempty"`
	// 消息内容
	Content string `json:"content,omitempty"`
	// 来源模块，可为空
	Source string `json:"source,omitempty"`
	// 来源业务对象 ID，可为空
	SourceID string `json:"source_id,omitempty"`
	// 消息元数据
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupportMessageQuery when eager-loading is set.
	Edges        SupportMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupportMessageEdges holds the relations/edges for other nodes in the graph.
type SupportMessageEdges struct {
	// Thread holds the value of the thread edge.
	Thread *SupportThread `json:"thread,omitempty"`
	// Sender holds the value of the sender edge.
	Sender *User `json:"sender,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ThreadOrErr returns the Thread value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportMessageEdges) ThreadOrErr() (*SupportThread, error) {
	if e.Thread != nil {
		return e.Thread, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: supportthread.Label}
	}
	return nil, &NotLoadedError{edge: "thread"}
}

// SenderOrErr returns the Sender value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportMessageEdges) SenderOrErr() (*User, error) {
	if e.Sender != nil {
		return e.Sender, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "sender"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupportMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supportmessage.FieldMetadata:
			values[i] = new([]byte)
		case supportmessage.FieldID, supportmessage.FieldThreadID, supportmessage.FieldSenderID:
			values[i] = new(sql.NullInt64)
		case supportmessage.FieldSenderType, supportmessage.FieldMessageType, supportmessage.FieldContentFormat, supportmessage.FieldTitle, supportmessage.FieldContent, supportmessage.FieldSource, supportmessage.FieldSourceID:
			values[i] = new(sql.NullString)
		case supportmessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupportMessage fields.
func (_m *SupportMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supportmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supportmessage.FieldThreadID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field thread_id", values[i])
			} else if value.Valid {
				_m.ThreadID = value.Int64
			}
		case supportmessage.FieldSenderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_type", values[i])
			} else if value.Valid {
				_m.SenderType = value.String
			}
		case supportmessage.FieldSenderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sender_id", values[i])
			} else if value.Valid {
				_m.SenderID = new(int64)
				*_m.SenderID = value.Int64
			}
		case supportmessage.FieldMessageType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_type", values[i])
			} else if value.Valid {
				_m.MessageType = value.String
			}
		case supportmessage.FieldContentFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_format", values[i])
			} else if value.Valid {
				_m.ContentFormat = value.String
			}
		case supportmessage.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case supportmessage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case supportmessage.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case supportmessage.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.String
			}
		case supportmessage.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case supportmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupportMessage.
// This includes values selected through modifiers, order, etc.
func (_m *SupportMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryThread queries the "thread" edge of the SupportMessage entity.
func (_m *SupportMessage) QueryThread() *SupportThreadQuery {
	return NewSupportMessageClient(_m.config).QueryThread(_m)
}

// QuerySender queries the "sender" edge of the SupportMessage entity.
func (_m *SupportMessage) QuerySender() *UserQuery {
	return NewSupportMessageClient(_m.config).QuerySender(_m)
}

// Update returns a builder for updating this SupportMessage.
// Note that you need to call SupportMessage.Unwrap() before calling this method if this SupportMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupportMessage) Update() *SupportMessageUpdateOne {
	return NewSupportMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupportMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupportMessage) Unwrap() *SupportMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupportMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupportMessage) String() string {
	var builder strings.Builder
	builder.WriteString("SupportMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("thread_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ThreadID))
	builder.WriteString(", ")
	builder.WriteString("sender_type=")
	builder.WriteString(_m.SenderType)
	builder.WriteString(", ")
	if v := _m.SenderID; v != nil {
		builder.WriteString("sender_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("message_type=")
	builder.WriteString(_m.MessageType)
	builder.WriteString(", ")
	builder.WriteString("content_format=")
	builder.WriteString(_m.ContentFormat)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(_m.SourceID)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupportMessages is a parsable slice of SupportMessage.
type SupportMessages []*SupportMessage
