// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/supportmessage"
	"github.com/Wei-Shaw/sub2api/ent/supportthread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportThreadCreate is the builder for creating a SupportThread entity.
type SupportThreadCreate struct {
	config
	mutation *SupportThreadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupportThreadCreate) SetCreatedAt(v time.Time) *SupportThreadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableCreatedAt(v *time.Time) *SupportThreadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SupportThreadCreate) SetUpdatedAt(v time.Time) *SupportThreadCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableUpdatedAt(v *time.Time) *SupportThreadCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SupportThreadCreate) SetUserID(v int64) *SupportThreadCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *SupportThreadCreate) SetSubject(v string) *SupportThreadCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableSubject(v *string) *SupportThreadCreate {
	if v != nil {
		_c.SetSubject(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SupportThreadCreate) SetStatus(v string) *SupportThreadCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableStatus(v *string) *SupportThreadCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *SupportThreadCreate) SetPriority(v string) *SupportThreadCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillablePriority(v *string) *SupportThreadCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *SupportThreadCreate) SetType(v string) *SupportThreadCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableType(v *string) *SupportThreadCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (_c *SupportThreadCreate) SetAssignedAdminID(v int64) *SupportThreadCreate {
	_c.mutation.SetAssignedAdminID(v)
	return _c
}

// SetNillableAssignedAdminID sets the "assigned_admin_id" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableAssignedAdminID(v *int64) *SupportThreadCreate {
	if v != nil {
		_c.SetAssignedAdminID(*v)
	}
	return _c
}

// SetLastMessageID sets the "last_message_id" field.
func (_c *SupportThreadCreate) SetLastMessageID(v int64) *SupportThreadCreate {
	_c.mutation.SetLastMessageID(v)
	return _c
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableLastMessageID(v *int64) *SupportThreadCreate {
	if v != nil {
		_c.SetLastMessageID(*v)
	}
	return _c
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (_c *SupportThreadCreate) SetLastMessageSenderType(v string) *SupportThreadCreate {
	_c.mutation.SetLastMessageSenderType(v)
	return _c
}

// SetNillableLastMessageSenderType sets the "last_message_sender_type" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableLastMessageSenderType(v *string) *SupportThreadCreate {
	if v != nil {
		_c.SetLastMessageSenderType(*v)
	}
	return _c
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (_c *SupportThreadCreate) SetLastMessageExcerpt(v string) *SupportThreadCreate {
	_c.mutation.SetLastMessageExcerpt(v)
	return _c
}

// SetNillableLastMessageExcerpt sets the "last_message_excerpt" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableLastMessageExcerpt(v *string) *SupportThreadCreate {
	if v != nil {
		_c.SetLastMessageExcerpt(*v)
	}
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *SupportThreadCreate) SetLastMessageAt(v time.Time) *SupportThreadCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableLastMessageAt(v *time.Time) *SupportThreadCreate {
	if v != nil {
		_c.SetLastMessageAt(*v)
	}
	return _c
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (_c *SupportThreadCreate) SetUserLastReadMessageID(v int64) *SupportThreadCreate {
	_c.mutation.SetUserLastReadMessageID(v)
	return _c
}

// SetNillableUserLastReadMessageID sets the "user_last_read_message_id" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableUserLastReadMessageID(v *int64) *SupportThreadCreate {
	if v != nil {
		_c.SetUserLastReadMessageID(*v)
	}
	return _c
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (_c *SupportThreadCreate) SetUserLastReadAt(v time.Time) *SupportThreadCreate {
	_c.mutation.SetUserLastReadAt(v)
	return _c
}

// SetNillableUserLastReadAt sets the "user_last_read_at" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableUserLastReadAt(v *time.Time) *SupportThreadCreate {
	if v != nil {
		_c.SetUserLastReadAt(*v)
	}
	return _c
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (_c *SupportThreadCreate) SetAdminLastReadMessageID(v int64) *SupportThreadCreate {
	_c.mutation.SetAdminLastReadMessageID(v)
	return _c
}

// SetNillableAdminLastReadMessageID sets the "admin_last_read_message_id" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableAdminLastReadMessageID(v *int64) *SupportThreadCreate {
	if v != nil {
		_c.SetAdminLastReadMessageID(*v)
	}
	return _c
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (_c *SupportThreadCreate) SetAdminLastReadAt(v time.Time) *SupportThreadCreate {
	_c.mutation.SetAdminLastReadAt(v)
	return _c
}

// SetNillableAdminLastReadAt sets the "admin_last_read_at" field if the given value is not nil.
func (_c *SupportThreadCreate) SetNillableAdminLastReadAt(v *time.Time) *SupportThreadCreate {
	if v != nil {
		_c.SetAdminLastReadAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SupportThreadCreate) SetUser(v *User) *SupportThreadCreate {
	return _c.SetUserID(v.ID)
}

// SetAssignedAdmin sets the "assigned_admin" edge to the User entity.
func (_c *SupportThreadCreate) SetAssignedAdmin(v *User) *SupportThreadCreate {
	return _c.SetAssignedAdminID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the SupportMessage entity by IDs.
func (_c *SupportThreadCreate) AddMessageIDs(ids ...int64) *SupportThreadCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the SupportMessage entity.
func (_c *SupportThreadCreate) AddMessages(v ...*SupportMessage) *SupportThreadCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the SupportThreadMutation object of the builder.
func (_c *SupportThreadCreate) Mutation() *SupportThreadMutation {
	return _c.mutation
}

// Save creates the SupportThread in the database.
func (_c *SupportThreadCreate) Save(ctx context.Context) (*SupportThread, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupportThreadCreate) SaveX(ctx context.Context) *SupportThread {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportThreadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportThreadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupportThreadCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supportthread.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := supportthread.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Subject(); !ok {
		v := supportthread.DefaultSubject
		_c.mutation.SetSubject(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := supportthread.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := supportthread.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := supportthread.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.LastMessageSenderType(); !ok {
		v := supportthread.DefaultLastMessageSenderType
		_c.mutation.SetLastMessageSenderType(v)
	}
	if _, ok := _c.mutation.LastMessageExcerpt(); !ok {
		v := supportthread.DefaultLastMessageExcerpt
		_c.mutation.SetLastMessageExcerpt(v)
	}
	if _, ok := _c.mutation.LastMessageAt(); !ok {
		v := supportthread.DefaultLastMessageAt()
		_c.mutation.SetLastMessageAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupportThreadCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupportThread.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SupportThread.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SupportThread.user_id"`)}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "SupportThread.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := supportthread.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SupportThread.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SupportThread.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := supportthread.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportThread.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "SupportThread.priority"`)}
	}
	if v, ok := _c.mutation.Priority(); ok {
		if err := supportthread.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportThread.priority": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "SupportThread.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := supportthread.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SupportThread.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastMessageSenderType(); !ok {
		return &ValidationError{Name: "last_message_sender_type", err: errors.New(`ent: missing required field "SupportThread.last_message_sender_type"`)}
	}
	if v, ok := _c.mutation.LastMessageSenderType(); ok {
		if err := supportthread.LastMessageSenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "last_message_sender_type", err: fmt.Errorf(`ent: validator failed for field "SupportThread.last_message_sender_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastMessageExcerpt(); !ok {
		return &ValidationError{Name: "last_message_excerpt", err: errors.New(`ent: missing required field "SupportThread.last_message_excerpt"`)}
	}
	if v, ok := _c.mutation.LastMessageExcerpt(); ok {
		if err := supportthread.LastMessageExcerptValidator(v); err != nil {
			return &ValidationError{Name: "last_message_excerpt", err: fmt.Errorf(`ent: validator failed for field "SupportThread.last_message_excerpt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastMessageAt(); !ok {
		return &ValidationError{Name: "last_message_at", err: errors.New(`ent: missing required field "SupportThread.last_message_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SupportThread.user"`)}
	}
	return nil
}

func (_c *SupportThreadCreate) sqlSave(ctx context.Context) (*SupportThread, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupportThreadCreate) createSpec() (*SupportThread, *sqlgraph.CreateSpec) {
	var (
		_node = &SupportThread{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supportthread.Table, sqlgraph.NewFieldSpec(supportthread.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supportthread.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(supportthread.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(supportthread.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(supportthread.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(supportthread.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(supportthread.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.LastMessageID(); ok {
		_spec.SetField(supportthread.FieldLastMessageID, field.TypeInt64, value)
		_node.LastMessageID = &value
	}
	if value, ok := _c.mutation.LastMessageSenderType(); ok {
		_spec.SetField(supportthread.FieldLastMessageSenderType, field.TypeString, value)
		_node.LastMessageSenderType = value
	}
	if value, ok := _c.mutation.LastMessageExcerpt(); ok {
		_spec.SetField(supportthread.FieldLastMessageExcerpt, field.TypeString, value)
		_node.LastMessageExcerpt = value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(supportthread.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = value
	}
	if value, ok := _c.mutation.UserLastReadMessageID(); ok {
		_spec.SetField(supportthread.FieldUserLastReadMessageID, field.TypeInt64, value)
		_node.UserLastReadMessageID = &value
	}
	if value, ok := _c.mutation.UserLastReadAt(); ok {
		_spec.SetField(supportthread.FieldUserLastReadAt, field.TypeTime, value)
		_node.UserLastReadAt = &value
	}
	if value, ok := _c.mutation.AdminLastReadMessageID(); ok {
		_spec.SetField(supportthread.FieldAdminLastReadMessageID, field.TypeInt64, value)
		_node.AdminLastReadMessageID = &value
	}
	if value, ok := _c.mutation.AdminLastReadAt(); ok {
		_spec.SetField(supportthread.FieldAdminLastReadAt, field.TypeTime, value)
		_node.AdminLastReadAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportthread.UserTable,
			Columns: []string{supportthread.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignedAdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportthread.AssignedAdminTable,
			Columns: []string{supportthread.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssignedAdminID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportthread.MessagesTable,
			Columns: []string{supportthread.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportThread.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportThreadUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportThreadCreate) OnConflict(opts ...sql.ConflictOption) *SupportThreadUpsertOne {
	_c.conflict = opts
	return &SupportThreadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportThread.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportThreadCreate) OnConflictColumns(columns ...string) *SupportThreadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportThreadUpsertOne{
		create: _c,
	}
}

type (
	// SupportThreadUpsertOne is the builder for "upsert"-ing
	//  one SupportThread node.
	SupportThreadUpsertOne struct {
		create *SupportThreadCreate
	}

	// SupportThreadUpsert is the "OnConflict" setter.
	SupportThreadUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportThreadUpsert) SetUpdatedAt(v time.Time) *SupportThreadUpsert {
	u.Set(supportthread.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateUpdatedAt() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SupportThreadUpsert) SetUserID(v int64) *SupportThreadUpsert {
	u.Set(supportthread.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateUserID() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldUserID)
	return u
}

// SetSubject sets the "subject" field.
func (u *SupportThreadUpsert) SetSubject(v string) *SupportThreadUpsert {
	u.Set(supportthread.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateSubject() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldSubject)
	return u
}

// SetStatus sets the "status" field.
func (u *SupportThreadUpsert) SetStatus(v string) *SupportThreadUpsert {
	u.Set(supportthread.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateStatus() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldStatus)
	return u
}

// SetPriority sets the "priority" field.
func (u *SupportThreadUpsert) SetPriority(v string) *SupportThreadUpsert {
	u.Set(supportthread.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdatePriority() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldPriority)
	return u
}

// SetType sets the "type" field.
func (u *SupportThreadUpsert) SetType(v string) *SupportThreadUpsert {
	u.Set(supportthread.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateType() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldType)
	return u
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (u *SupportThreadUpsert) SetAssignedAdminID(v int64) *SupportThreadUpsert {
	u.Set(supportthread.FieldAssignedAdminID, v)
	return u
}

// UpdateAssignedAdminID sets the "assigned_admin_id" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateAssignedAdminID() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldAssignedAdminID)
	return u
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (u *SupportThreadUpsert) ClearAssignedAdminID() *SupportThreadUpsert {
	u.SetNull(supportthread.FieldAssignedAdminID)
	return u
}

// SetLastMessageID sets the "last_message_id" field.
func (u *SupportThreadUpsert) SetLastMessageID(v int64) *SupportThreadUpsert {
	u.Set(supportthread.FieldLastMessageID, v)
	return u
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateLastMessageID() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldLastMessageID)
	return u
}

// AddLastMessageID adds v to the "last_message_id" field.
func (u *SupportThreadUpsert) AddLastMessageID(v int64) *SupportThreadUpsert {
	u.Add(supportthread.FieldLastMessageID, v)
	return u
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *SupportThreadUpsert) ClearLastMessageID() *SupportThreadUpsert {
	u.SetNull(supportthread.FieldLastMessageID)
	return u
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (u *SupportThreadUpsert) SetLastMessageSenderType(v string) *SupportThreadUpsert {
	u.Set(supportthread.FieldLastMessageSenderType, v)
	return u
}

// UpdateLastMessageSenderType sets the "last_message_sender_type" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateLastMessageSenderType() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldLastMessageSenderType)
	return u
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (u *SupportThreadUpsert) SetLastMessageExcerpt(v string) *SupportThreadUpsert {
	u.Set(supportthread.FieldLastMessageExcerpt, v)
	return u
}

// UpdateLastMessageExcerpt sets the "last_message_excerpt" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateLastMessageExcerpt() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldLastMessageExcerpt)
	return u
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *SupportThreadUpsert) SetLastMessageAt(v time.Time) *SupportThreadUpsert {
	u.Set(supportthread.FieldLastMessageAt, v)
	return u
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateLastMessageAt() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldLastMessageAt)
	return u
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (u *SupportThreadUpsert) SetUserLastReadMessageID(v int64) *SupportThreadUpsert {
	u.Set(supportthread.FieldUserLastReadMessageID, v)
	return u
}

// UpdateUserLastReadMessageID sets the "user_last_read_message_id" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateUserLastReadMessageID() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldUserLastReadMessageID)
	return u
}

// AddUserLastReadMessageID adds v to the "user_last_read_message_id" field.
func (u *SupportThreadUpsert) AddUserLastReadMessageID(v int64) *SupportThreadUpsert {
	u.Add(supportthread.FieldUserLastReadMessageID, v)
	return u
}

// ClearUserLastReadMessageID clears the value of the "user_last_read_message_id" field.
func (u *SupportThreadUpsert) ClearUserLastReadMessageID() *SupportThreadUpsert {
	u.SetNull(supportthread.FieldUserLastReadMessageID)
	return u
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (u *SupportThreadUpsert) SetUserLastReadAt(v time.Time) *SupportThreadUpsert {
	u.Set(supportthread.FieldUserLastReadAt, v)
	return u
}

// UpdateUserLastReadAt sets the "user_last_read_at" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateUserLastReadAt() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldUserLastReadAt)
	return u
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (u *SupportThreadUpsert) ClearUserLastReadAt() *SupportThreadUpsert {
	u.SetNull(supportthread.FieldUserLastReadAt)
	return u
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (u *SupportThreadUpsert) SetAdminLastReadMessageID(v int64) *SupportThreadUpsert {
	u.Set(supportthread.FieldAdminLastReadMessageID, v)
	return u
}

// UpdateAdminLastReadMessageID sets the "admin_last_read_message_id" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateAdminLastReadMessageID() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldAdminLastReadMessageID)
	return u
}

// AddAdminLastReadMessageID adds v to the "admin_last_read_message_id" field.
func (u *SupportThreadUpsert) AddAdminLastReadMessageID(v int64) *SupportThreadUpsert {
	u.Add(supportthread.FieldAdminLastReadMessageID, v)
	return u
}

// ClearAdminLastReadMessageID clears the value of the "admin_last_read_message_id" field.
func (u *SupportThreadUpsert) ClearAdminLastReadMessageID() *SupportThreadUpsert {
	u.SetNull(supportthread.FieldAdminLastReadMessageID)
	return u
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (u *SupportThreadUpsert) SetAdminLastReadAt(v time.Time) *SupportThreadUpsert {
	u.Set(supportthread.FieldAdminLastReadAt, v)
	return u
}

// UpdateAdminLastReadAt sets the "admin_last_read_at" field to the value that was provided on create.
func (u *SupportThreadUpsert) UpdateAdminLastReadAt() *SupportThreadUpsert {
	u.SetExcluded(supportthread.FieldAdminLastReadAt)
	return u
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (u *SupportThreadUpsert) ClearAdminLastReadAt() *SupportThreadUpsert {
	u.SetNull(supportthread.FieldAdminLastReadAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SupportThread.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportThreadUpsertOne) UpdateNewValues() *SupportThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supportthread.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportThread.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupportThreadUpsertOne) Ignore() *SupportThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportThreadUpsertOne) DoNothing() *SupportThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportThreadCreate.OnConflict
// documentation for more info.
func (u *SupportThreadUpsertOne) Update(set func(*SupportThreadUpsert)) *SupportThreadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportThreadUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportThreadUpsertOne) SetUpdatedAt(v time.Time) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateUpdatedAt() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SupportThreadUpsertOne) SetUserID(v int64) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateUserID() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateUserID()
	})
}

// SetSubject sets the "subject" field.
func (u *SupportThreadUpsertOne) SetSubject(v string) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateSubject() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateSubject()
	})
}

// SetStatus sets the "status" field.
func (u *SupportThreadUpsertOne) SetStatus(v string) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateStatus() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateStatus()
	})
}

// SetPriority sets the "priority" field.
func (u *SupportThreadUpsertOne) SetPriority(v string) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdatePriority() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdatePriority()
	})
}

// SetType sets the "type" field.
func (u *SupportThreadUpsertOne) SetType(v string) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateType() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateType()
	})
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (u *SupportThreadUpsertOne) SetAssignedAdminID(v int64) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetAssignedAdminID(v)
	})
}

// UpdateAssignedAdminID sets the "assigned_admin_id" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateAssignedAdminID() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateAssignedAdminID()
	})
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (u *SupportThreadUpsertOne) ClearAssignedAdminID() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearAssignedAdminID()
	})
}

// SetLastMessageID sets the "last_message_id" field.
func (u *SupportThreadUpsertOne) SetLastMessageID(v int64) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetLastMessageID(v)
	})
}

// AddLastMessageID adds v to the "last_message_id" field.
func (u *SupportThreadUpsertOne) AddLastMessageID(v int64) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.AddLastMessageID(v)
	})
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateLastMessageID() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateLastMessageID()
	})
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *SupportThreadUpsertOne) ClearLastMessageID() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearLastMessageID()
	})
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (u *SupportThreadUpsertOne) SetLastMessageSenderType(v string) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetLastMessageSenderType(v)
	})
}

// UpdateLastMessageSenderType sets the "last_message_sender_type" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateLastMessageSenderType() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateLastMessageSenderType()
	})
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (u *SupportThreadUpsertOne) SetLastMessageExcerpt(v string) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetLastMessageExcerpt(v)
	})
}

// UpdateLastMessageExcerpt sets the "last_message_excerpt" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateLastMessageExcerpt() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateLastMessageExcerpt()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *SupportThreadUpsertOne) SetLastMessageAt(v time.Time) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateLastMessageAt() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateLastMessageAt()
	})
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (u *SupportThreadUpsertOne) SetUserLastReadMessageID(v int64) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetUserLastReadMessageID(v)
	})
}

// AddUserLastReadMessageID adds v to the "user_last_read_message_id" field.
func (u *SupportThreadUpsertOne) AddUserLastReadMessageID(v int64) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.AddUserLastReadMessageID(v)
	})
}

// UpdateUserLastReadMessageID sets the "user_last_read_message_id" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateUserLastReadMessageID() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateUserLastReadMessageID()
	})
}

// ClearUserLastReadMessageID clears the value of the "user_last_read_message_id" field.
func (u *SupportThreadUpsertOne) ClearUserLastReadMessageID() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearUserLastReadMessageID()
	})
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (u *SupportThreadUpsertOne) SetUserLastReadAt(v time.Time) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetUserLastReadAt(v)
	})
}

// UpdateUserLastReadAt sets the "user_last_read_at" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateUserLastReadAt() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateUserLastReadAt()
	})
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (u *SupportThreadUpsertOne) ClearUserLastReadAt() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearUserLastReadAt()
	})
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (u *SupportThreadUpsertOne) SetAdminLastReadMessageID(v int64) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetAdminLastReadMessageID(v)
	})
}

// AddAdminLastReadMessageID adds v to the "admin_last_read_message_id" field.
func (u *SupportThreadUpsertOne) AddAdminLastReadMessageID(v int64) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.AddAdminLastReadMessageID(v)
	})
}

// UpdateAdminLastReadMessageID sets the "admin_last_read_message_id" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateAdminLastReadMessageID() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateAdminLastReadMessageID()
	})
}

// ClearAdminLastReadMessageID clears the value of the "admin_last_read_message_id" field.
func (u *SupportThreadUpsertOne) ClearAdminLastReadMessageID() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearAdminLastReadMessageID()
	})
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (u *SupportThreadUpsertOne) SetAdminLastReadAt(v time.Time) *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetAdminLastReadAt(v)
	})
}

// UpdateAdminLastReadAt sets the "admin_last_read_at" field to the value that was provided on create.
func (u *SupportThreadUpsertOne) UpdateAdminLastReadAt() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateAdminLastReadAt()
	})
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (u *SupportThreadUpsertOne) ClearAdminLastReadAt() *SupportThreadUpsertOne {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearAdminLastReadAt()
	})
}

// Exec executes the query.
func (u *SupportThreadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportThreadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportThreadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupportThreadUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupportThreadUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupportThreadCreateBulk is the builder for creating many SupportThread entities in bulk.
type SupportThreadCreateBulk struct {
	config
	err      error
	builders []*SupportThreadCreate
	conflict []sql.ConflictOption
}

// Save creates the SupportThread entities in the database.
func (_c *SupportThreadCreateBulk) Save(ctx context.Context) ([]*SupportThread, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupportThread, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupportThreadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupportThreadCreateBulk) SaveX(ctx context.Context) []*SupportThread {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportThreadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportThreadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportThread.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportThreadUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportThreadCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupportThreadUpsertBulk {
	_c.conflict = opts
	return &SupportThreadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportThread.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportThreadCreateBulk) OnConflictColumns(columns ...string) *SupportThreadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportThreadUpsertBulk{
		create: _c,
	}
}

// SupportThreadUpsertBulk is the builder for "upsert"-ing
// a bulk of SupportThread nodes.
type SupportThreadUpsertBulk struct {
	create *SupportThreadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupportThread.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportThreadUpsertBulk) UpdateNewValues() *SupportThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supportthread.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportThread.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupportThreadUpsertBulk) Ignore() *SupportThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportThreadUpsertBulk) DoNothing() *SupportThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportThreadCreateBulk.OnConflict
// documentation for more info.
func (u *SupportThreadUpsertBulk) Update(set func(*SupportThreadUpsert)) *SupportThreadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportThreadUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportThreadUpsertBulk) SetUpdatedAt(v time.Time) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateUpdatedAt() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SupportThreadUpsertBulk) SetUserID(v int64) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateUserID() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateUserID()
	})
}

// SetSubject sets the "subject" field.
func (u *SupportThreadUpsertBulk) SetSubject(v string) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateSubject() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateSubject()
	})
}

// SetStatus sets the "status" field.
func (u *SupportThreadUpsertBulk) SetStatus(v string) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateStatus() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateStatus()
	})
}

// SetPriority sets the "priority" field.
func (u *SupportThreadUpsertBulk) SetPriority(v string) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdatePriority() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdatePriority()
	})
}

// SetType sets the "type" field.
func (u *SupportThreadUpsertBulk) SetType(v string) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateType() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateType()
	})
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (u *SupportThreadUpsertBulk) SetAssignedAdminID(v int64) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetAssignedAdminID(v)
	})
}

// UpdateAssignedAdminID sets the "assigned_admin_id" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateAssignedAdminID() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateAssignedAdminID()
	})
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (u *SupportThreadUpsertBulk) ClearAssignedAdminID() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearAssignedAdminID()
	})
}

// SetLastMessageID sets the "last_message_id" field.
func (u *SupportThreadUpsertBulk) SetLastMessageID(v int64) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetLastMessageID(v)
	})
}

// AddLastMessageID adds v to the "last_message_id" field.
func (u *SupportThreadUpsertBulk) AddLastMessageID(v int64) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.AddLastMessageID(v)
	})
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateLastMessageID() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateLastMessageID()
	})
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *SupportThreadUpsertBulk) ClearLastMessageID() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearLastMessageID()
	})
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (u *SupportThreadUpsertBulk) SetLastMessageSenderType(v string) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetLastMessageSenderType(v)
	})
}

// UpdateLastMessageSenderType sets the "last_message_sender_type" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateLastMessageSenderType() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateLastMessageSenderType()
	})
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (u *SupportThreadUpsertBulk) SetLastMessageExcerpt(v string) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetLastMessageExcerpt(v)
	})
}

// UpdateLastMessageExcerpt sets the "last_message_excerpt" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateLastMessageExcerpt() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateLastMessageExcerpt()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *SupportThreadUpsertBulk) SetLastMessageAt(v time.Time) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateLastMessageAt() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateLastMessageAt()
	})
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (u *SupportThreadUpsertBulk) SetUserLastReadMessageID(v int64) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetUserLastReadMessageID(v)
	})
}

// AddUserLastReadMessageID adds v to the "user_last_read_message_id" field.
func (u *SupportThreadUpsertBulk) AddUserLastReadMessageID(v int64) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.AddUserLastReadMessageID(v)
	})
}

// UpdateUserLastReadMessageID sets the "user_last_read_message_id" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateUserLastReadMessageID() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateUserLastReadMessageID()
	})
}

// ClearUserLastReadMessageID clears the value of the "user_last_read_message_id" field.
func (u *SupportThreadUpsertBulk) ClearUserLastReadMessageID() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearUserLastReadMessageID()
	})
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (u *SupportThreadUpsertBulk) SetUserLastReadAt(v time.Time) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetUserLastReadAt(v)
	})
}

// UpdateUserLastReadAt sets the "user_last_read_at" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateUserLastReadAt() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateUserLastReadAt()
	})
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (u *SupportThreadUpsertBulk) ClearUserLastReadAt() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearUserLastReadAt()
	})
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (u *SupportThreadUpsertBulk) SetAdminLastReadMessageID(v int64) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetAdminLastReadMessageID(v)
	})
}

// AddAdminLastReadMessageID adds v to the "admin_last_read_message_id" field.
func (u *SupportThreadUpsertBulk) AddAdminLastReadMessageID(v int64) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.AddAdminLastReadMessageID(v)
	})
}

// UpdateAdminLastReadMessageID sets the "admin_last_read_message_id" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateAdminLastReadMessageID() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateAdminLastReadMessageID()
	})
}

// ClearAdminLastReadMessageID clears the value of the "admin_last_read_message_id" field.
func (u *SupportThreadUpsertBulk) ClearAdminLastReadMessageID() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearAdminLastReadMessageID()
	})
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (u *SupportThreadUpsertBulk) SetAdminLastReadAt(v time.Time) *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.SetAdminLastReadAt(v)
	})
}

// UpdateAdminLastReadAt sets the "admin_last_read_at" field to the value that was provided on create.
func (u *SupportThreadUpsertBulk) UpdateAdminLastReadAt() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.UpdateAdminLastReadAt()
	})
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (u *SupportThreadUpsertBulk) ClearAdminLastReadAt() *SupportThreadUpsertBulk {
	return u.Update(func(s *SupportThreadUpsert) {
		s.ClearAdminLastReadAt()
	})
}

// Exec executes the query.
func (u *SupportThreadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupportThreadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportThreadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportThreadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
