// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportmessage"
	"github.com/Wei-Shaw/sub2api/ent/supportthread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportMessageUpdate is the builder for updating SupportMessage entities.
type SupportMessageUpdate struct {
	config
	hooks    []Hook
	mutation *SupportMessageMutation
}

// Where appends a list predicates to the SupportMessageUpdate builder.
func (_u *SupportMessageUpdate) Where(ps ...predicate.SupportMessage) *SupportMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetThreadID sets the "thread_id" field.
func (_u *SupportMessageUpdate) SetThreadID(v int64) *SupportMessageUpdate {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableThreadID(v *int64) *SupportMessageUpdate {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// SetSenderType sets the "sender_type" field.
func (_u *SupportMessageUpdate) SetSenderType(v string) *SupportMessageUpdate {
	_u.mutation.SetSenderType(v)
	return _u
}

// SetNillableSenderType sets the "sender_type" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableSenderType(v *string) *SupportMessageUpdate {
	if v != nil {
		_u.SetSenderType(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *SupportMessageUpdate) SetSenderID(v int64) *SupportMessageUpdate {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableSenderID(v *int64) *SupportMessageUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// ClearSenderID clears the value of the "sender_id" field.
func (_u *SupportMessageUpdate) ClearSenderID() *SupportMessageUpdate {
	_u.mutation.ClearSenderID()
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *SupportMessageUpdate) SetMessageType(v string) *SupportMessageUpdate {
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableMessageType(v *string) *SupportMessageUpdate {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// SetContentFormat sets the "content_format" field.
func (_u *SupportMessageUpdate) SetContentFormat(v string) *SupportMessageUpdate {
	_u.mutation.SetContentFormat(v)
	return _u
}

// SetNillableContentFormat sets the "content_format" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableContentFormat(v *string) *SupportMessageUpdate {
	if v != nil {
		_u.SetContentFormat(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SupportMessageUpdate) SetTitle(v string) *SupportMessageUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableTitle(v *string) *SupportMessageUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SupportMessageUpdate) SetContent(v string) *SupportMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableContent(v *string) *SupportMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *SupportMessageUpdate) SetSource(v string) *SupportMessageUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableSource(v *string) *SupportMessageUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *SupportMessageUpdate) SetSourceID(v string) *SupportMessageUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableSourceID(v *string) *SupportMessageUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SupportMessageUpdate) SetMetadata(v map[string]interface{}) *SupportMessageUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SupportMessageUpdate) ClearMetadata() *SupportMessageUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetThread sets the "thread" edge to the SupportThread entity.
func (_u *SupportMessageUpdate) SetThread(v *SupportThread) *SupportMessageUpdate {
	return _u.SetThreadID(v.ID)
}

// SetSender sets the "sender" edge to the User entity.
func (_u *SupportMessageUpdate) SetSender(v *User) *SupportMessageUpdate {
	return _u.SetSenderID(v.ID)
}

// Mutation returns the SupportMessageMutation object of the builder.
func (_u *SupportMessageUpdate) Mutation() *SupportMessageMutation {
	return _u.mutation
}

// ClearThread clears the "thread" edge to the SupportThread entity.
func (_u *SupportMessageUpdate) ClearThread() *SupportMessageUpdate {
	_u.mutation.ClearThread()
	return _u
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *SupportMessageUpdate) ClearSender() *SupportMessageUpdate {
	_u.mutation.ClearSender()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportMessageUpdate) check() error {
	if v, ok := _u.mutation.SenderType(); ok {
		if err := supportmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MessageType(); ok {
		if err := supportmessage.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.message_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentFormat(); ok {
		if err := supportmessage.ContentFormatValidator(v); err != nil {
			return &ValidationError{Name: "content_format", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.content_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := supportmessage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := supportmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := supportmessage.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := supportmessage.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.source_id": %w`, err)}
		}
	}
	if _u.mutation.ThreadCleared() && len(_u.mutation.ThreadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportMessage.thread"`)
	}
	return nil
}

func (_u *SupportMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportmessage.Table, supportmessage.Columns, sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SenderType(); ok {
		_spec.SetField(supportmessage.FieldSenderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(supportmessage.FieldMessageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentFormat(); ok {
		_spec.SetField(supportmessage.FieldContentFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportmessage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(supportmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(supportmessage.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(supportmessage.FieldSourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(supportmessage.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(supportmessage.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ThreadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.ThreadTable,
			Columns: []string{supportmessage.ThreadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportthread.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThreadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.ThreadTable,
			Columns: []string{supportmessage.ThreadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportthread.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.SenderTable,
			Columns: []string{supportmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.SenderTable,
			Columns: []string{supportmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportMessageUpdateOne is the builder for updating a single SupportMessage entity.
type SupportMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportMessageMutation
}

// SetThreadID sets the "thread_id" field.
func (_u *SupportMessageUpdateOne) SetThreadID(v int64) *SupportMessageUpdateOne {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableThreadID(v *int64) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// SetSenderType sets the "sender_type" field.
func (_u *SupportMessageUpdateOne) SetSenderType(v string) *SupportMessageUpdateOne {
	_u.mutation.SetSenderType(v)
	return _u
}

// SetNillableSenderType sets the "sender_type" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableSenderType(v *string) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetSenderType(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *SupportMessageUpdateOne) SetSenderID(v int64) *SupportMessageUpdateOne {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableSenderID(v *int64) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// ClearSenderID clears the value of the "sender_id" field.
func (_u *SupportMessageUpdateOne) ClearSenderID() *SupportMessageUpdateOne {
	_u.mutation.ClearSenderID()
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *SupportMessageUpdateOne) SetMessageType(v string) *SupportMessageUpdateOne {
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableMessageType(v *string) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// SetContentFormat sets the "content_format" field.
func (_u *SupportMessageUpdateOne) SetContentFormat(v string) *SupportMessageUpdateOne {
	_u.mutation.SetContentFormat(v)
	return _u
}

// SetNillableContentFormat sets the "content_format" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableContentFormat(v *string) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetContentFormat(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SupportMessageUpdateOne) SetTitle(v string) *SupportMessageUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableTitle(v *string) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SupportMessageUpdateOne) SetContent(v string) *SupportMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableContent(v *string) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *SupportMessageUpdateOne) SetSource(v string) *SupportMessageUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableSource(v *string) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *SupportMessageUpdateOne) SetSourceID(v string) *SupportMessageUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableSourceID(v *string) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SupportMessageUpdateOne) SetMetadata(v map[string]interface{}) *SupportMessageUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SupportMessageUpdateOne) ClearMetadata() *SupportMessageUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetThread sets the "thread" edge to the SupportThread entity.
func (_u *SupportMessageUpdateOne) SetThread(v *SupportThread) *SupportMessageUpdateOne {
	return _u.SetThreadID(v.ID)
}

// SetSender sets the "sender" edge to the User entity.
func (_u *SupportMessageUpdateOne) SetSender(v *User) *SupportMessageUpdateOne {
	return _u.SetSenderID(v.ID)
}

// Mutation returns the SupportMessageMutation object of the builder.
func (_u *SupportMessageUpdateOne) Mutation() *SupportMessageMutation {
	return _u.mutation
}

// ClearThread clears the "thread" edge to the SupportThread entity.
func (_u *SupportMessageUpdateOne) ClearThread() *SupportMessageUpdateOne {
	_u.mutation.ClearThread()
	return _u
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *SupportMessageUpdateOne) ClearSender() *SupportMessageUpdateOne {
	_u.mutation.ClearSender()
	return _u
}

// Where appends a list predicates to the SupportMessageUpdate builder.
func (_u *SupportMessageUpdateOne) Where(ps ...predicate.SupportMessage) *SupportMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportMessageUpdateOne) Select(field string, fields ...string) *SupportMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportMessage entity.
func (_u *SupportMessageUpdateOne) Save(ctx context.Context) (*SupportMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportMessageUpdateOne) SaveX(ctx context.Context) *SupportMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportMessageUpdateOne) check() error {
	if v, ok := _u.mutation.SenderType(); ok {
		if err := supportmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MessageType(); ok {
		if err := supportmessage.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.message_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentFormat(); ok {
		if err := supportmessage.ContentFormatValidator(v); err != nil {
			return &ValidationError{Name: "content_format", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.content_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := supportmessage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := supportmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := supportmessage.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := supportmessage.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.source_id": %w`, err)}
		}
	}
	if _u.mutation.ThreadCleared() && len(_u.mutation.ThreadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportMessage.thread"`)
	}
	return nil
}

func (_u *SupportMessageUpdateOne) sqlSave(ctx context.Context) (_node *SupportMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportmessage.Table, supportmessage.Columns, sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportmessage.FieldID)
		for _, f := range fields {
			if !supportmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SenderType(); ok {
		_spec.SetField(supportmessage.FieldSenderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(supportmessage.FieldMessageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentFormat(); ok {
		_spec.SetField(supportmessage.FieldContentFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportmessage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(supportmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(supportmessage.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(supportmessage.FieldSourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(supportmessage.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(supportmessage.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ThreadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.ThreadTable,
			Columns: []string{supportmessage.ThreadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportthread.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThreadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.ThreadTable,
			Columns: []string{supportmessage.ThreadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportthread.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.SenderTable,
			Columns: []string{supportmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.SenderTable,
			Columns: []string{supportmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
