// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/supportmessage"
	"github.com/Wei-Shaw/sub2api/ent/supportthread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportMessageCreate is the builder for creating a SupportMessage entity.
type SupportMessageCreate struct {
	config
	mutation *SupportMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetThreadID sets the "thread_id" field.
func (_c *SupportMessageCreate) SetThreadID(v int64) *SupportMessageCreate {
	_c.mutation.SetThreadID(v)
	return _c
}

// SetSenderType sets the "sender_type" field.
func (_c *SupportMessageCreate) SetSenderType(v string) *SupportMessageCreate {
	_c.mutation.SetSenderType(v)
	return _c
}

// SetSenderID sets the "sender_id" field.
func (_c *SupportMessageCreate) SetSenderID(v int64) *SupportMessageCreate {
	_c.mutation.SetSenderID(v)
	return _c
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_c *SupportMessageCreate) SetNillableSenderID(v *int64) *SupportMessageCreate {
	if v != nil {
		_c.SetSenderID(*v)
	}
	return _c
}

// SetMessageType sets the "message_type" field.
func (_c *SupportMessageCreate) SetMessageType(v string) *SupportMessageCreate {
	_c.mutation.SetMessageType(v)
	return _c
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_c *SupportMessageCreate) SetNillableMessageType(v *string) *SupportMessageCreate {
	if v != nil {
		_c.SetMessageType(*v)
	}
	return _c
}

// SetContentFormat sets the "content_format" field.
func (_c *SupportMessageCreate) SetContentFormat(v string) *SupportMessageCreate {
	_c.mutation.SetContentFormat(v)
	return _c
}

// SetNillableContentFormat sets the "content_format" field if the given value is not nil.
func (_c *SupportMessageCreate) SetNillableContentFormat(v *string) *SupportMessageCreate {
	if v != nil {
		_c.SetContentFormat(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *SupportMessageCreate) SetTitle(v string) *SupportMessageCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *SupportMessageCreate) SetNillableTitle(v *string) *SupportMessageCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *SupportMessageCreate) SetContent(v string) *SupportMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *SupportMessageCreate) SetSource(v string) *SupportMessageCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *SupportMessageCreate) SetNillableSource(v *string) *SupportMessageCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *SupportMessageCreate) SetSourceID(v string) *SupportMessageCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *SupportMessageCreate) SetNillableSourceID(v *string) *SupportMessageCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SupportMessageCreate) SetMetadata(v map[string]interface{}) *SupportMessageCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupportMessageCreate) SetCreatedAt(v time.Time) *SupportMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupportMessageCreate) SetNillableCreatedAt(v *time.Time) *SupportMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetThread sets the "thread" edge to the SupportThread entity.
func (_c *SupportMessageCreate) SetThread(v *SupportThread) *SupportMessageCreate {
	return _c.SetThreadID(v.ID)
}

// SetSender sets the "sender" edge to the User entity.
func (_c *SupportMessageCreate) SetSender(v *User) *SupportMessageCreate {
	return _c.SetSenderID(v.ID)
}

// Mutation returns the SupportMessageMutation object of the builder.
func (_c *SupportMessageCreate) Mutation() *SupportMessageMutation {
	return _c.mutation
}

// Save creates the SupportMessage in the database.
func (_c *SupportMessageCreate) Save(ctx context.Context) (*SupportMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupportMessageCreate) SaveX(ctx context.Context) *SupportMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupportMessageCreate) defaults() {
	if _, ok := _c.mutation.MessageType(); !ok {
		v := supportmessage.DefaultMessageType
		_c.mutation.SetMessageType(v)
	}
	if _, ok := _c.mutation.ContentFormat(); !ok {
		v := supportmessage.DefaultContentFormat
		_c.mutation.SetContentFormat(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := supportmessage.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := supportmessage.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		v := supportmessage.DefaultSourceID
		_c.mutation.SetSourceID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supportmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupportMessageCreate) check() error {
	if _, ok := _c.mutation.ThreadID(); !ok {
		return &ValidationError{Name: "thread_id", err: errors.New(`ent: missing required field "SupportMessage.thread_id"`)}
	}
	if _, ok := _c.mutation.SenderType(); !ok {
		return &ValidationError{Name: "sender_type", err: errors.New(`ent: missing required field "SupportMessage.sender_type"`)}
	}
	if v, ok := _c.mutation.SenderType(); ok {
		if err := supportmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.sender_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MessageType(); !ok {
		return &ValidationError{Name: "message_type", err: errors.New(`ent: missing required field "SupportMessage.message_type"`)}
	}
	if v, ok := _c.mutation.MessageType(); ok {
		if err := supportmessage.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.message_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentFormat(); !ok {
		return &ValidationError{Name: "content_format", err: errors.New(`ent: missing required field "SupportMessage.content_format"`)}
	}
	if v, ok := _c.mutation.ContentFormat(); ok {
		if err := supportmessage.ContentFormatValidator(v); err != nil {
			return &ValidationError{Name: "content_format", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.content_format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "SupportMessage.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := supportmessage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "SupportMessage.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := supportmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "SupportMessage.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := supportmessage.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "SupportMessage.source_id"`)}
	}
	if v, ok := _c.mutation.SourceID(); ok {
		if err := supportmessage.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.source_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupportMessage.created_at"`)}
	}
	if len(_c.mutation.ThreadIDs()) == 0 {
		return &ValidationError{Name: "thread", err: errors.New(`ent: missing required edge "SupportMessage.thread"`)}
	}
	return nil
}

func (_c *SupportMessageCreate) sqlSave(ctx context.Context) (*SupportMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupportMessageCreate) createSpec() (*SupportMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &SupportMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supportmessage.Table, sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SenderType(); ok {
		_spec.SetField(supportmessage.FieldSenderType, field.TypeString, value)
		_node.SenderType = value
	}
	if value, ok := _c.mutation.MessageType(); ok {
		_spec.SetField(supportmessage.FieldMessageType, field.TypeString, value)
		_node.MessageType = value
	}
	if value, ok := _c.mutation.ContentFormat(); ok {
		_spec.SetField(supportmessage.FieldContentFormat, field.TypeString, value)
		_node.ContentFormat = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(supportmessage.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(supportmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(supportmessage.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(supportmessage.FieldSourceID, field.TypeString, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(supportmessage.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supportmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ThreadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.ThreadTable,
			Columns: []string{supportmessage.ThreadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportthread.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ThreadID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.SenderTable,
			Columns: []string{supportmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SenderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportMessage.Create().
//		SetThreadID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportMessageUpsert) {
//			SetThreadID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportMessageCreate) OnConflict(opts ...sql.ConflictOption) *SupportMessageUpsertOne {
	_c.conflict = opts
	return &SupportMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportMessageCreate) OnConflictColumns(columns ...string) *SupportMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportMessageUpsertOne{
		create: _c,
	}
}

type (
	// SupportMessageUpsertOne is the builder for "upsert"-ing
	//  one SupportMessage node.
	SupportMessageUpsertOne struct {
		create *SupportMessageCreate
	}

	// SupportMessageUpsert is the "OnConflict" setter.
	SupportMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetThreadID sets the "thread_id" field.
func (u *SupportMessageUpsert) SetThreadID(v int64) *SupportMessageUpsert {
	u.Set(supportmessage.FieldThreadID, v)
	return u
}

// UpdateThreadID sets the "thread_id" field to the value that was provided on create.
func (u *SupportMessageUpsert) UpdateThreadID() *SupportMessageUpsert {
	u.SetExcluded(supportmessage.FieldThreadID)
	return u
}

// SetSenderType sets the "sender_type" field.
func (u *SupportMessageUpsert) SetSenderType(v string) *SupportMessageUpsert {
	u.Set(supportmessage.FieldSenderType, v)
	return u
}

// UpdateSenderType sets the "sender_type" field to the value that was provided on create.
func (u *SupportMessageUpsert) UpdateSenderType() *SupportMessageUpsert {
	u.SetExcluded(supportmessage.FieldSenderType)
	return u
}

// SetSenderID sets the "sender_id" field.
func (u *SupportMessageUpsert) SetSenderID(v int64) *SupportMessageUpsert {
	u.Set(supportmessage.FieldSenderID, v)
	return u
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *SupportMessageUpsert) UpdateSenderID() *SupportMessageUpsert {
	u.SetExcluded(supportmessage.FieldSenderID)
	return u
}

// ClearSenderID clears the value of the "sender_id" field.
func (u *SupportMessageUpsert) ClearSenderID() *SupportMessageUpsert {
	u.SetNull(supportmessage.FieldSenderID)
	return u
}

// SetMessageType sets the "message_type" field.
func (u *SupportMessageUpsert) SetMessageType(v string) *SupportMessageUpsert {
	u.Set(supportmessage.FieldMessageType, v)
	return u
}

// UpdateMessageType sets the "message_type" field to the value that was provided on create.
func (u *SupportMessageUpsert) UpdateMessageType() *SupportMessageUpsert {
	u.SetExcluded(supportmessage.FieldMessageType)
	return u
}

// SetContentFormat sets the "content_format" field.
func (u *SupportMessageUpsert) SetContentFormat(v string) *SupportMessageUpsert {
	u.Set(supportmessage.FieldContentFormat, v)
	return u
}

// UpdateContentFormat sets the "content_format" field to the value that was provided on create.
func (u *SupportMessageUpsert) UpdateContentFormat() *SupportMessageUpsert {
	u.SetExcluded(supportmessage.FieldContentFormat)
	return u
}

// SetTitle sets the "title" field.
func (u *SupportMessageUpsert) SetTitle(v string) *SupportMessageUpsert {
	u.Set(supportmessage.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SupportMessageUpsert) UpdateTitle() *SupportMessageUpsert {
	u.SetExcluded(supportmessage.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *SupportMessageUpsert) SetContent(v string) *SupportMessageUpsert {
	u.Set(supportmessage.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SupportMessageUpsert) UpdateContent() *SupportMessageUpsert {
	u.SetExcluded(supportmessage.FieldContent)
	return u
}

// SetSource sets the "source" field.
func (u *SupportMessageUpsert) SetSource(v string) *SupportMessageUpsert {
	u.Set(supportmessage.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SupportMessageUpsert) UpdateSource() *SupportMessageUpsert {
	u.SetExcluded(supportmessage.FieldSource)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *SupportMessageUpsert) SetSourceID(v string) *SupportMessageUpsert {
	u.Set(supportmessage.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *SupportMessageUpsert) UpdateSourceID() *SupportMessageUpsert {
	u.SetExcluded(supportmessage.FieldSourceID)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *SupportMessageUpsert) SetMetadata(v map[string]interface{}) *SupportMessageUpsert {
	u.Set(supportmessage.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SupportMessageUpsert) UpdateMetadata() *SupportMessageUpsert {
	u.SetExcluded(supportmessage.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *SupportMessageUpsert) ClearMetadata() *SupportMessageUpsert {
	u.SetNull(supportmessage.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SupportMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportMessageUpsertOne) UpdateNewValues() *SupportMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supportmessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupportMessageUpsertOne) Ignore() *SupportMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportMessageUpsertOne) DoNothing() *SupportMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportMessageCreate.OnConflict
// documentation for more info.
func (u *SupportMessageUpsertOne) Update(set func(*SupportMessageUpsert)) *SupportMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetThreadID sets the "thread_id" field.
func (u *SupportMessageUpsertOne) SetThreadID(v int64) *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetThreadID(v)
	})
}

// UpdateThreadID sets the "thread_id" field to the value that was provided on create.
func (u *SupportMessageUpsertOne) UpdateThreadID() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateThreadID()
	})
}

// SetSenderType sets the "sender_type" field.
func (u *SupportMessageUpsertOne) SetSenderType(v string) *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetSenderType(v)
	})
}

// UpdateSenderType sets the "sender_type" field to the value that was provided on create.
func (u *SupportMessageUpsertOne) UpdateSenderType() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateSenderType()
	})
}

// SetSenderID sets the "sender_id" field.
func (u *SupportMessageUpsertOne) SetSenderID(v int64) *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetSenderID(v)
	})
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *SupportMessageUpsertOne) UpdateSenderID() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateSenderID()
	})
}

// ClearSenderID clears the value of the "sender_id" field.
func (u *SupportMessageUpsertOne) ClearSenderID() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.ClearSenderID()
	})
}

// SetMessageType sets the "message_type" field.
func (u *SupportMessageUpsertOne) SetMessageType(v string) *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetMessageType(v)
	})
}

// UpdateMessageType sets the "message_type" field to the value that was provided on create.
func (u *SupportMessageUpsertOne) UpdateMessageType() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateMessageType()
	})
}

// SetContentFormat sets the "content_format" field.
func (u *SupportMessageUpsertOne) SetContentFormat(v string) *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetContentFormat(v)
	})
}

// UpdateContentFormat sets the "content_format" field to the value that was provided on create.
func (u *SupportMessageUpsertOne) UpdateContentFormat() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateContentFormat()
	})
}

// SetTitle sets the "title" field.
func (u *SupportMessageUpsertOne) SetTitle(v string) *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SupportMessageUpsertOne) UpdateTitle() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *SupportMessageUpsertOne) SetContent(v string) *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SupportMessageUpsertOne) UpdateContent() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateContent()
	})
}

// SetSource sets the "source" field.
func (u *SupportMessageUpsertOne) SetSource(v string) *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SupportMessageUpsertOne) UpdateSource() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateSource()
	})
}

// SetSourceID sets the "source_id" field.
func (u *SupportMessageUpsertOne) SetSourceID(v string) *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *SupportMessageUpsertOne) UpdateSourceID() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateSourceID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SupportMessageUpsertOne) SetMetadata(v map[string]interface{}) *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SupportMessageUpsertOne) UpdateMetadata() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *SupportMessageUpsertOne) ClearMetadata() *SupportMessageUpsertOne {
	return u.Update(func(s *SupportMessageUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *SupportMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupportMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupportMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupportMessageCreateBulk is the builder for creating many SupportMessage entities in bulk.
type SupportMessageCreateBulk struct {
	config
	err      error
	builders []*SupportMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the SupportMessage entities in the database.
func (_c *SupportMessageCreateBulk) Save(ctx context.Context) ([]*SupportMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupportMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupportMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupportMessageCreateBulk) SaveX(ctx context.Context) []*SupportMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportMessageUpsert) {
//			SetThreadID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupportMessageUpsertBulk {
	_c.conflict = opts
	return &SupportMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportMessageCreateBulk) OnConflictColumns(columns ...string) *SupportMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportMessageUpsertBulk{
		create: _c,
	}
}

// SupportMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of SupportMessage nodes.
type SupportMessageUpsertBulk struct {
	create *SupportMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupportMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportMessageUpsertBulk) UpdateNewValues() *SupportMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supportmessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupportMessageUpsertBulk) Ignore() *SupportMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportMessageUpsertBulk) DoNothing() *SupportMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportMessageCreateBulk.OnConflict
// documentation for more info.
func (u *SupportMessageUpsertBulk) Update(set func(*SupportMessageUpsert)) *SupportMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetThreadID sets the "thread_id" field.
func (u *SupportMessageUpsertBulk) SetThreadID(v int64) *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetThreadID(v)
	})
}

// UpdateThreadID sets the "thread_id" field to the value that was provided on create.
func (u *SupportMessageUpsertBulk) UpdateThreadID() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateThreadID()
	})
}

// SetSenderType sets the "sender_type" field.
func (u *SupportMessageUpsertBulk) SetSenderType(v string) *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetSenderType(v)
	})
}

// UpdateSenderType sets the "sender_type" field to the value that was provided on create.
func (u *SupportMessageUpsertBulk) UpdateSenderType() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateSenderType()
	})
}

// SetSenderID sets the "sender_id" field.
func (u *SupportMessageUpsertBulk) SetSenderID(v int64) *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetSenderID(v)
	})
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *SupportMessageUpsertBulk) UpdateSenderID() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateSenderID()
	})
}

// ClearSenderID clears the value of the "sender_id" field.
func (u *SupportMessageUpsertBulk) ClearSenderID() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.ClearSenderID()
	})
}

// SetMessageType sets the "message_type" field.
func (u *SupportMessageUpsertBulk) SetMessageType(v string) *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetMessageType(v)
	})
}

// UpdateMessageType sets the "message_type" field to the value that was provided on create.
func (u *SupportMessageUpsertBulk) UpdateMessageType() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateMessageType()
	})
}

// SetContentFormat sets the "content_format" field.
func (u *SupportMessageUpsertBulk) SetContentFormat(v string) *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetContentFormat(v)
	})
}

// UpdateContentFormat sets the "content_format" field to the value that was provided on create.
func (u *SupportMessageUpsertBulk) UpdateContentFormat() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateContentFormat()
	})
}

// SetTitle sets the "title" field.
func (u *SupportMessageUpsertBulk) SetTitle(v string) *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SupportMessageUpsertBulk) UpdateTitle() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *SupportMessageUpsertBulk) SetContent(v string) *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SupportMessageUpsertBulk) UpdateContent() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateContent()
	})
}

// SetSource sets the "source" field.
func (u *SupportMessageUpsertBulk) SetSource(v string) *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SupportMessageUpsertBulk) UpdateSource() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateSource()
	})
}

// SetSourceID sets the "source_id" field.
func (u *SupportMessageUpsertBulk) SetSourceID(v string) *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *SupportMessageUpsertBulk) UpdateSourceID() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateSourceID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SupportMessageUpsertBulk) SetMetadata(v map[string]interface{}) *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SupportMessageUpsertBulk) UpdateMetadata() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *SupportMessageUpsertBulk) ClearMetadata() *SupportMessageUpsertBulk {
	return u.Update(func(s *SupportMessageUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *SupportMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupportMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
