// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/supportthread"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportThread is the model entity for the SupportThread schema.
type SupportThread struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 工单服务所属用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 线程展示标题
	Subject string `json:"subject,omitempty"`
	// 当前人工工单状态: open, pending_user, pending_admin, resolved, closed
	Status string `json:"status,omitempty"`
	// 当前人工工单优先级: low, normal, high, urgent
	Priority string `json:"priority,omitempty"`
	// 当前人工工单类型: support, notice, billing, subscription, account, security
	Type string `json:"type,omitempty"`
	// 负责人管理员 ID
	AssignedAdminID *int64 `json:"assigned_admin_id,omitempty"`
	// 最后一条消息 ID
	LastMessageID *int64 `json:"last_message_id,omitempty"`
	// 最后一条消息发送方
	LastMessageSenderType string `json:"last_message_sender_type,omitempty"`
	// 最后一条消息摘要
	LastMessageExcerpt string `json:"last_message_excerpt,omitempty"`
	// 最后消息时间
	LastMessageAt time.Time `json:"last_message_at,omitempty"`
	// 用户最后已读消息 ID
	UserLastReadMessageID *int64 `json:"user_last_read_message_id,omitempty"`
	// 用户最后已读时间
	UserLastReadAt *time.Time `json:"user_last_read_at,omitempty"`
	// 管理员侧最后已读消息 ID
	AdminLastReadMessageID *int64 `json:"admin_last_read_message_id,omitempty"`
	// 管理员侧最后已读时间
	AdminLastReadAt *time.Time `json:"admin_last_read_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupportThreadQuery when eager-loading is set.
	Edges        SupportThreadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupportThreadEdges holds the relations/edges for other nodes in the graph.
type SupportThreadEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// AssignedAdmin holds the value of the assigned_admin edge.
	AssignedAdmin *User `json:"assigned_admin,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*SupportMessage `json:"messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportThreadEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AssignedAdminOrErr returns the AssignedAdmin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportThreadEdges) AssignedAdminOrErr() (*User, error) {
	if e.AssignedAdmin != nil {
		return e.AssignedAdmin, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "assigned_admin"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e SupportThreadEdges) MessagesOrErr() ([]*SupportMessage, error) {
	if e.loadedTypes[2] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupportThread) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supportthread.FieldID, supportthread.FieldUserID, supportthread.FieldAssignedAdminID, supportthread.FieldLastMessageID, supportthread.FieldUserLastReadMessageID, supportthread.FieldAdminLastReadMessageID:
			values[i] = new(sql.NullInt64)
		case supportthread.FieldSubject, supportthread.FieldStatus, supportthread.FieldPriority, supportthread.FieldType, supportthread.FieldLastMessageSenderType, supportthread.FieldLastMessageExcerpt:
			values[i] = new(sql.NullString)
		case supportthread.FieldCreatedAt, supportthread.FieldUpdatedAt, supportthread.FieldLastMessageAt, supportthread.FieldUserLastReadAt, supportthread.FieldAdminLastReadAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupportThread fields.
func (_m *SupportThread) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supportthread.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supportthread.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case supportthread.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case supportthread.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case supportthread.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case supportthread.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case supportthread.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = value.String
			}
		case supportthread.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case supportthread.FieldAssignedAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_admin_id", values[i])
			} else if value.Valid {
				_m.AssignedAdminID = new(int64)
				*_m.AssignedAdminID = value.Int64
			}
		case supportthread.FieldLastMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_id", values[i])
			} else if value.Valid {
				_m.LastMessageID = new(int64)
				*_m.LastMessageID = value.Int64
			}
		case supportthread.FieldLastMessageSenderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_sender_type", values[i])
			} else if value.Valid {
				_m.LastMessageSenderType = value.String
			}
		case supportthread.FieldLastMessageExcerpt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_excerpt", values[i])
			} else if value.Valid {
				_m.LastMessageExcerpt = value.String
			}
		case supportthread.FieldLastMessageAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_at", values[i])
			} else if value.Valid {
				_m.LastMessageAt = value.Time
			}
		case supportthread.FieldUserLastReadMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_last_read_message_id", values[i])
			} else if value.Valid {
				_m.UserLastReadMessageID = new(int64)
				*_m.UserLastReadMessageID = value.Int64
			}
		case supportthread.FieldUserLastReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field user_last_read_at", values[i])
			} else if value.Valid {
				_m.UserLastReadAt = new(time.Time)
				*_m.UserLastReadAt = value.Time
			}
		case supportthread.FieldAdminLastReadMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_last_read_message_id", values[i])
			} else if value.Valid {
				_m.AdminLastReadMessageID = new(int64)
				*_m.AdminLastReadMessageID = value.Int64
			}
		case supportthread.FieldAdminLastReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field admin_last_read_at", values[i])
			} else if value.Valid {
				_m.AdminLastReadAt = new(time.Time)
				*_m.AdminLastReadAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupportThread.
// This includes values selected through modifiers, order, etc.
func (_m *SupportThread) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SupportThread entity.
func (_m *SupportThread) QueryUser() *UserQuery {
	return NewSupportThreadClient(_m.config).QueryUser(_m)
}

// QueryAssignedAdmin queries the "assigned_admin" edge of the SupportThread entity.
func (_m *SupportThread) QueryAssignedAdmin() *UserQuery {
	return NewSupportThreadClient(_m.config).QueryAssignedAdmin(_m)
}

// QueryMessages queries the "messages" edge of the SupportThread entity.
func (_m *SupportThread) QueryMessages() *SupportMessageQuery {
	return NewSupportThreadClient(_m.config).QueryMessages(_m)
}

// Update returns a builder for updating this SupportThread.
// Note that you need to call SupportThread.Unwrap() before calling this method if this SupportThread
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupportThread) Update() *SupportThreadUpdateOne {
	return NewSupportThreadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupportThread entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupportThread) Unwrap() *SupportThread {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupportThread is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupportThread) String() string {
	var builder strings.Builder
	builder.WriteString("SupportThread(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(_m.Priority)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	if v := _m.AssignedAdminID; v != nil {
		builder.WriteString("assigned_admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastMessageID; v != nil {
		builder.WriteString("last_message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("last_message_sender_type=")
	builder.WriteString(_m.LastMessageSenderType)
	builder.WriteString(", ")
	builder.WriteString("last_message_excerpt=")
	builder.WriteString(_m.LastMessageExcerpt)
	builder.WriteString(", ")
	builder.WriteString("last_message_at=")
	builder.WriteString(_m.LastMessageAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UserLastReadMessageID; v != nil {
		builder.WriteString("user_last_read_message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserLastReadAt; v != nil {
		builder.WriteString("user_last_read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AdminLastReadMessageID; v != nil {
		builder.WriteString("admin_last_read_message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AdminLastReadAt; v != nil {
		builder.WriteString("admin_last_read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SupportThreads is a parsable slice of SupportThread.
type SupportThreads []*SupportThread
