<template>
  <article class="community-form profile-wallet">
    <header class="wallet-head"><div><p class="community-eyebrow">PAYOUT</p><h2>余额提现与收款码</h2><p>管理员审核后线下打款。最低 1.00 元，金额最多保留两位小数；每 7 天最多提交 3 次。</p></div><span class="community-chip community-chip--yellow">{{pending?'待结算':'可提交'}}</span></header>
    <section class="wallet-summary"><div><span>当前余额</span><strong>¥{{money(balance)}}</strong></div><div><span>提现状态</span><strong>{{pending?'已有待结算申请':'可提交'}}</strong></div><div><span>近 7 天申请</span><strong>{{recentCount}} / 3</strong></div></section>
    <div class="community-tabs"><button v-for="entry in methods" :key="entry.key" :class="{active:method===entry.key}" @click="method=entry.key">{{entry.label}}</button></div>
    <section class="wallet-grid"><div class="wallet-submit"><div><h3>提交提现</h3><p>同一用户只能保留一笔待结算提现。</p></div><label>提现金额<input v-model.number="amount" class="community-input" type="number" min="1" step="0.01" /></label><label>备注<input v-model.trim="note" class="community-input" placeholder="可选" /></label><div class="wallet-breakdown"><div><span>提现金额</span><strong>¥{{money(validAmount)}}</strong></div><div><span>首次手续费</span><strong>¥{{money(firstFee)}}</strong></div><div><span>本次扣除</span><strong>¥{{money(totalDeduction)}}</strong></div></div><p v-if="!saved" class="wallet-warning">请先上传并保存本次要使用的{{methodLabel}}收款码。</p><p v-else-if="!canSubmit" class="wallet-warning">请检查金额、余额、提交次数或待结算申请。</p><button class="community-btn" :disabled="!canSubmit||submitting" @click="submit">{{submitting?'提交中...':'提交提现申请'}}</button></div>
      <div class="wallet-method"><div><h3>收款码管理</h3><p>提交提现时会保存本次收款码快照，后续修改不会影响申请。</p></div><div class="wallet-qr"><img v-if="qrData" :src="qrData" alt="当前收款码"/><div v-else><strong>未上传{{methodLabel}}收款码</strong><span>当前方式还未保存收款码</span></div></div><label class="community-btn community-btn--quiet wallet-upload"><input type="file" accept="image/png,image/jpeg,image/webp" @change="readQR"/>上传收款码</label><div class="community-toolbar"><button class="community-btn" :disabled="!qrData" @click="saveMethod">保存</button><button class="community-btn community-btn--danger" :disabled="!saved||pendingForMethod" @click="removeMethod">删除</button></div></div></section>
    <section><div class="wallet-history-head"><div><h3>提现记录</h3><p>待结算申请可取消，取消后金额退回余额。</p></div><span>最近 {{withdrawals.length}} 笔</span></div><div class="community-table-wrap"><table class="community-table"><thead><tr><th>金额 / 手续费</th><th>方式</th><th>状态</th><th>申请时间</th><th>审核备注</th><th>操作</th></tr></thead><tbody><tr v-if="withdrawals.length===0"><td colspan="6"><div class="community-empty compact">暂无提现记录</div></td></tr><tr v-for="withdrawal in withdrawals" v-else :key="withdrawal.id"><td>¥{{money(withdrawal.amount)}} <small v-if="withdrawal.fee">+ ¥{{money(withdrawal.fee)}}</small></td><td>{{withdrawal.payout_method==='alipay'?'支付宝':'微信'}}</td><td><span class="community-status" :class="`community-status--${withdrawal.status}`">{{statusText(withdrawal.status)}}</span></td><td>{{format(withdrawal.created_at)}}</td><td>{{withdrawal.admin_note||withdrawal.payment_reference||'-'}}</td><td><button v-if="withdrawal.status==='pending'" class="community-btn community-btn--danger" @click="cancel(withdrawal.id)">取消申请</button></td></tr></tbody></table></div></section>
  </article>
</template>
<script setup lang="ts">
import{computed,onMounted,ref,watch}from'vue'
import{communityAPI,type PayoutMethod,type Withdrawal}from'@/api/community'
import{useAppStore}from'@/stores/app'
import{useAuthStore}from'@/stores/auth'
const app=useAppStore(),auth=useAuthStore(),method=ref<'alipay'|'wechat'>('alipay'),methods=[{key:'alipay',label:'支付宝'},{key:'wechat',label:'微信'}]as const,items=ref<PayoutMethod[]>([]),withdrawals=ref<Withdrawal[]>([]),qrData=ref(''),amount=ref(1),note=ref(''),submitting=ref(false)
const balance=computed(()=>Number(auth.user?.balance||0)),saved=computed(()=>items.value.some(item=>item.method===method.value)),pending=computed(()=>withdrawals.value.some(item=>['pending','approved'].includes(item.status))),pendingForMethod=computed(()=>withdrawals.value.some(item=>item.payout_method===method.value&&['pending','approved'].includes(item.status))),recentCount=computed(()=>withdrawals.value.filter(item=>Date.now()-new Date(item.created_at).getTime()<=7*86400000).length),firstFee=computed(()=>withdrawals.value.length===0?.1:0),validAmount=computed(()=>Number.isFinite(amount.value)?Math.max(0,Math.round(amount.value*100)/100):0),totalDeduction=computed(()=>validAmount.value+firstFee.value),canSubmit=computed(()=>saved.value&&!pending.value&&recentCount.value<3&&validAmount.value>=1&&totalDeduction.value<=balance.value),methodLabel=computed(()=>method.value==='alipay'?'支付宝':'微信')
const money=(value:number)=>Number(value||0).toFixed(2),format=(value:string)=>new Date(value).toLocaleString('zh-CN'),statusText=(value:string)=>({pending:'待审核',approved:'待打款',paid:'已打款',rejected:'已驳回',cancelled:'已取消'} as Record<string,string>)[value]||value
function sync(){const current=items.value.find(item=>item.method===method.value);qrData.value=current?.qr_code_data||''}
watch(method,sync)
async function load(){try{[items.value,withdrawals.value]=await Promise.all([communityAPI.payoutMethods(),communityAPI.withdrawals()]);sync()}catch{app.showError('提现信息加载失败')}}
function readQR(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>2*1024*1024){app.showError('收款码不能超过 2MB');return}const reader=new FileReader();reader.onload=()=>{qrData.value=String(reader.result||'')};reader.readAsDataURL(file)}
async function saveMethod(){try{await communityAPI.savePayoutMethod({method:method.value,qr_code_data:qrData.value,display_name:''});await load();app.showSuccess('收款码已保存')}catch{app.showError('收款码保存失败')}}
async function removeMethod(){if(!confirm(`确认删除${methodLabel.value}收款码？`))return;try{await communityAPI.deletePayoutMethod(method.value);await load();app.showSuccess('收款码已删除')}catch{app.showError('存在待结算申请时不能删除收款码')}}
async function submit(){if(!canSubmit.value)return;submitting.value=true;try{await communityAPI.createWithdrawal({method:method.value,amount:validAmount.value,note:note.value});amount.value=1;note.value='';await load();await auth.refreshUser();app.showSuccess('提现申请已提交，金额已冻结')}catch{app.showError('提交失败，请检查余额、次数或待处理申请')}finally{submitting.value=false}}
async function cancel(id:number){if(!confirm('取消后冻结金额将退回余额，确认继续？'))return;try{await communityAPI.cancelWithdrawal(id);await load();await auth.refreshUser();app.showSuccess('申请已取消，金额已退回')}catch{app.showError('取消失败')}}
onMounted(load)
</script>
<style src="@/styles/community.css"></style>
<style scoped>.profile-wallet{grid-column:1/-1}.wallet-head,.wallet-history-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.wallet-head>div,.wallet-history-head>div{display:grid;gap:5px}.wallet-head p,.wallet-history-head p,.wallet-submit>div p,.wallet-method>div p{color:var(--muted);font-size:.74rem}.wallet-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border:1px solid var(--line);border-radius:var(--community-radius-lg);background:var(--community-surface);overflow:hidden}.wallet-summary>div{display:grid;gap:4px;border-right:1px solid var(--line);padding:12px}.wallet-summary>div:last-child{border:0}.wallet-summary span{color:var(--muted);font-size:.68rem}.wallet-summary strong{font-size:1rem}.wallet-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.wallet-submit,.wallet-method{display:grid;align-content:start;gap:11px;border:1px solid var(--line);border-radius:var(--community-radius-lg);background:var(--community-surface);padding:14px}.wallet-submit>div:first-child,.wallet-method>div:first-child{display:grid;gap:5px}.wallet-breakdown{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-radius:var(--community-radius);background:var(--community-surface-muted);overflow:hidden}.wallet-breakdown>div{display:grid;gap:3px;padding:9px}.wallet-breakdown span{color:var(--muted);font-size:.65rem}.wallet-warning{color:#b54708;font-size:.72rem}.wallet-qr{display:grid;place-items:center;min-height:180px;border:1px dashed var(--community-control-line);border-radius:var(--community-radius);background:var(--community-surface-muted)}.wallet-qr img{width:180px;height:180px;object-fit:contain}.wallet-qr>div{display:grid;gap:5px;color:var(--muted);text-align:center}.wallet-upload{position:relative;overflow:hidden}.wallet-upload input{position:absolute;inset:0;cursor:pointer;opacity:0}.wallet-history-head>span{color:var(--muted);font-size:.72rem}@media(max-width:760px){.wallet-head,.wallet-history-head{flex-direction:column}.wallet-summary,.wallet-grid{grid-template-columns:1fr}.wallet-summary>div{border-right:0;border-bottom:1px solid var(--line)}.wallet-breakdown{grid-template-columns:1fr}}</style>
