// Code generated by ent, DO NOT EDIT.

package supportthread

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the supportthread type in the database.
	Label = "support_thread"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldAssignedAdminID holds the string denoting the assigned_admin_id field in the database.
	FieldAssignedAdminID = "assigned_admin_id"
	// FieldLastMessageID holds the string denoting the last_message_id field in the database.
	FieldLastMessageID = "last_message_id"
	// FieldLastMessageSenderType holds the string denoting the last_message_sender_type field in the database.
	FieldLastMessageSenderType = "last_message_sender_type"
	// FieldLastMessageExcerpt holds the string denoting the last_message_excerpt field in the database.
	FieldLastMessageExcerpt = "last_message_excerpt"
	// FieldLastMessageAt holds the string denoting the last_message_at field in the database.
	FieldLastMessageAt = "last_message_at"
	// FieldUserLastReadMessageID holds the string denoting the user_last_read_message_id field in the database.
	FieldUserLastReadMessageID = "user_last_read_message_id"
	// FieldUserLastReadAt holds the string denoting the user_last_read_at field in the database.
	FieldUserLastReadAt = "user_last_read_at"
	// FieldAdminLastReadMessageID holds the string denoting the admin_last_read_message_id field in the database.
	FieldAdminLastReadMessageID = "admin_last_read_message_id"
	// FieldAdminLastReadAt holds the string denoting the admin_last_read_at field in the database.
	FieldAdminLastReadAt = "admin_last_read_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAssignedAdmin holds the string denoting the assigned_admin edge name in mutations.
	EdgeAssignedAdmin = "assigned_admin"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// Table holds the table name of the supportthread in the database.
	Table = "support_threads"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "support_threads"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// AssignedAdminTable is the table that holds the assigned_admin relation/edge.
	AssignedAdminTable = "support_threads"
	// AssignedAdminInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AssignedAdminInverseTable = "users"
	// AssignedAdminColumn is the table column denoting the assigned_admin relation/edge.
	AssignedAdminColumn = "assigned_admin_id"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "support_messages"
	// MessagesInverseTable is the table name for the SupportMessage entity.
	// It exists in this package in order to avoid circular dependency with the "supportmessage" package.
	MessagesInverseTable = "support_messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "thread_id"
)

// Columns holds all SQL columns for supportthread fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldSubject,
	FieldStatus,
	FieldPriority,
	FieldType,
	FieldAssignedAdminID,
	FieldLastMessageID,
	FieldLastMessageSenderType,
	FieldLastMessageExcerpt,
	FieldLastMessageAt,
	FieldUserLastReadMessageID,
	FieldUserLastReadAt,
	FieldAdminLastReadMessageID,
	FieldAdminLastReadAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultSubject holds the default value on creation for the "subject" field.
	DefaultSubject string
	// SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	SubjectValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority string
	// PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	PriorityValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultLastMessageSenderType holds the default value on creation for the "last_message_sender_type" field.
	DefaultLastMessageSenderType string
	// LastMessageSenderTypeValidator is a validator for the "last_message_sender_type" field. It is called by the builders before save.
	LastMessageSenderTypeValidator func(string) error
	// DefaultLastMessageExcerpt holds the default value on creation for the "last_message_excerpt" field.
	DefaultLastMessageExcerpt string
	// LastMessageExcerptValidator is a validator for the "last_message_excerpt" field. It is called by the builders before save.
	LastMessageExcerptValidator func(string) error
	// DefaultLastMessageAt holds the default value on creation for the "last_message_at" field.
	DefaultLastMessageAt func() time.Time
)

// OrderOption defines the ordering options for the SupportThread queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByAssignedAdminID orders the results by the assigned_admin_id field.
func ByAssignedAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedAdminID, opts...).ToFunc()
}

// ByLastMessageID orders the results by the last_message_id field.
func ByLastMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageID, opts...).ToFunc()
}

// ByLastMessageSenderType orders the results by the last_message_sender_type field.
func ByLastMessageSenderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageSenderType, opts...).ToFunc()
}

// ByLastMessageExcerpt orders the results by the last_message_excerpt field.
func ByLastMessageExcerpt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageExcerpt, opts...).ToFunc()
}

// ByLastMessageAt orders the results by the last_message_at field.
func ByLastMessageAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageAt, opts...).ToFunc()
}

// ByUserLastReadMessageID orders the results by the user_last_read_message_id field.
func ByUserLastReadMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserLastReadMessageID, opts...).ToFunc()
}

// ByUserLastReadAt orders the results by the user_last_read_at field.
func ByUserLastReadAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserLastReadAt, opts...).ToFunc()
}

// ByAdminLastReadMessageID orders the results by the admin_last_read_message_id field.
func ByAdminLastReadMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminLastReadMessageID, opts...).ToFunc()
}

// ByAdminLastReadAt orders the results by the admin_last_read_at field.
func ByAdminLastReadAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminLastReadAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAssignedAdminField orders the results by assigned_admin field.
func ByAssignedAdminField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssignedAdminStep(), sql.OrderByField(field, opts...))
	}
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newAssignedAdminStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssignedAdminInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AssignedAdminTable, AssignedAdminColumn),
	)
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
