// Code generated by ent, DO NOT EDIT.

package supportmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLTE(FieldID, id))
}

// ThreadID applies equality check predicate on the "thread_id" field. It's identical to ThreadIDEQ.
func ThreadID(v int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldThreadID, v))
}

// SenderType applies equality check predicate on the "sender_type" field. It's identical to SenderTypeEQ.
func SenderType(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldSenderType, v))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldSenderID, v))
}

// MessageType applies equality check predicate on the "message_type" field. It's identical to MessageTypeEQ.
func MessageType(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldMessageType, v))
}

// ContentFormat applies equality check predicate on the "content_format" field. It's identical to ContentFormatEQ.
func ContentFormat(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldContentFormat, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldContent, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldSource, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldSourceID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// ThreadIDEQ applies the EQ predicate on the "thread_id" field.
func ThreadIDEQ(v int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldThreadID, v))
}

// ThreadIDNEQ applies the NEQ predicate on the "thread_id" field.
func ThreadIDNEQ(v int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNEQ(FieldThreadID, v))
}

// ThreadIDIn applies the In predicate on the "thread_id" field.
func ThreadIDIn(vs ...int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIn(FieldThreadID, vs...))
}

// ThreadIDNotIn applies the NotIn predicate on the "thread_id" field.
func ThreadIDNotIn(vs ...int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotIn(FieldThreadID, vs...))
}

// SenderTypeEQ applies the EQ predicate on the "sender_type" field.
func SenderTypeEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldSenderType, v))
}

// SenderTypeNEQ applies the NEQ predicate on the "sender_type" field.
func SenderTypeNEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNEQ(FieldSenderType, v))
}

// SenderTypeIn applies the In predicate on the "sender_type" field.
func SenderTypeIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIn(FieldSenderType, vs...))
}

// SenderTypeNotIn applies the NotIn predicate on the "sender_type" field.
func SenderTypeNotIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotIn(FieldSenderType, vs...))
}

// SenderTypeGT applies the GT predicate on the "sender_type" field.
func SenderTypeGT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGT(FieldSenderType, v))
}

// SenderTypeGTE applies the GTE predicate on the "sender_type" field.
func SenderTypeGTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGTE(FieldSenderType, v))
}

// SenderTypeLT applies the LT predicate on the "sender_type" field.
func SenderTypeLT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLT(FieldSenderType, v))
}

// SenderTypeLTE applies the LTE predicate on the "sender_type" field.
func SenderTypeLTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLTE(FieldSenderType, v))
}

// SenderTypeContains applies the Contains predicate on the "sender_type" field.
func SenderTypeContains(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContains(FieldSenderType, v))
}

// SenderTypeHasPrefix applies the HasPrefix predicate on the "sender_type" field.
func SenderTypeHasPrefix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasPrefix(FieldSenderType, v))
}

// SenderTypeHasSuffix applies the HasSuffix predicate on the "sender_type" field.
func SenderTypeHasSuffix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasSuffix(FieldSenderType, v))
}

// SenderTypeEqualFold applies the EqualFold predicate on the "sender_type" field.
func SenderTypeEqualFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEqualFold(FieldSenderType, v))
}

// SenderTypeContainsFold applies the ContainsFold predicate on the "sender_type" field.
func SenderTypeContainsFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContainsFold(FieldSenderType, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...int64) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotIn(FieldSenderID, vs...))
}

// SenderIDIsNil applies the IsNil predicate on the "sender_id" field.
func SenderIDIsNil() predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIsNull(FieldSenderID))
}

// SenderIDNotNil applies the NotNil predicate on the "sender_id" field.
func SenderIDNotNil() predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotNull(FieldSenderID))
}

// MessageTypeEQ applies the EQ predicate on the "message_type" field.
func MessageTypeEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldMessageType, v))
}

// MessageTypeNEQ applies the NEQ predicate on the "message_type" field.
func MessageTypeNEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNEQ(FieldMessageType, v))
}

// MessageTypeIn applies the In predicate on the "message_type" field.
func MessageTypeIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIn(FieldMessageType, vs...))
}

// MessageTypeNotIn applies the NotIn predicate on the "message_type" field.
func MessageTypeNotIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotIn(FieldMessageType, vs...))
}

// MessageTypeGT applies the GT predicate on the "message_type" field.
func MessageTypeGT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGT(FieldMessageType, v))
}

// MessageTypeGTE applies the GTE predicate on the "message_type" field.
func MessageTypeGTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGTE(FieldMessageType, v))
}

// MessageTypeLT applies the LT predicate on the "message_type" field.
func MessageTypeLT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLT(FieldMessageType, v))
}

// MessageTypeLTE applies the LTE predicate on the "message_type" field.
func MessageTypeLTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLTE(FieldMessageType, v))
}

// MessageTypeContains applies the Contains predicate on the "message_type" field.
func MessageTypeContains(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContains(FieldMessageType, v))
}

// MessageTypeHasPrefix applies the HasPrefix predicate on the "message_type" field.
func MessageTypeHasPrefix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasPrefix(FieldMessageType, v))
}

// MessageTypeHasSuffix applies the HasSuffix predicate on the "message_type" field.
func MessageTypeHasSuffix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasSuffix(FieldMessageType, v))
}

// MessageTypeEqualFold applies the EqualFold predicate on the "message_type" field.
func MessageTypeEqualFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEqualFold(FieldMessageType, v))
}

// MessageTypeContainsFold applies the ContainsFold predicate on the "message_type" field.
func MessageTypeContainsFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContainsFold(FieldMessageType, v))
}

// ContentFormatEQ applies the EQ predicate on the "content_format" field.
func ContentFormatEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldContentFormat, v))
}

// ContentFormatNEQ applies the NEQ predicate on the "content_format" field.
func ContentFormatNEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNEQ(FieldContentFormat, v))
}

// ContentFormatIn applies the In predicate on the "content_format" field.
func ContentFormatIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIn(FieldContentFormat, vs...))
}

// ContentFormatNotIn applies the NotIn predicate on the "content_format" field.
func ContentFormatNotIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotIn(FieldContentFormat, vs...))
}

// ContentFormatGT applies the GT predicate on the "content_format" field.
func ContentFormatGT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGT(FieldContentFormat, v))
}

// ContentFormatGTE applies the GTE predicate on the "content_format" field.
func ContentFormatGTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGTE(FieldContentFormat, v))
}

// ContentFormatLT applies the LT predicate on the "content_format" field.
func ContentFormatLT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLT(FieldContentFormat, v))
}

// ContentFormatLTE applies the LTE predicate on the "content_format" field.
func ContentFormatLTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLTE(FieldContentFormat, v))
}

// ContentFormatContains applies the Contains predicate on the "content_format" field.
func ContentFormatContains(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContains(FieldContentFormat, v))
}

// ContentFormatHasPrefix applies the HasPrefix predicate on the "content_format" field.
func ContentFormatHasPrefix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasPrefix(FieldContentFormat, v))
}

// ContentFormatHasSuffix applies the HasSuffix predicate on the "content_format" field.
func ContentFormatHasSuffix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasSuffix(FieldContentFormat, v))
}

// ContentFormatEqualFold applies the EqualFold predicate on the "content_format" field.
func ContentFormatEqualFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEqualFold(FieldContentFormat, v))
}

// ContentFormatContainsFold applies the ContainsFold predicate on the "content_format" field.
func ContentFormatContainsFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContainsFold(FieldContentFormat, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContainsFold(FieldContent, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContainsFold(FieldSource, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldContainsFold(FieldSourceID, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportMessage {
	return predicate.SupportMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasThread applies the HasEdge predicate on the "thread" edge.
func HasThread() predicate.SupportMessage {
	return predicate.SupportMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ThreadTable, ThreadColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasThreadWith applies the HasEdge predicate on the "thread" edge with a given conditions (other predicates).
func HasThreadWith(preds ...predicate.SupportThread) predicate.SupportMessage {
	return predicate.SupportMessage(func(s *sql.Selector) {
		step := newThreadStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSender applies the HasEdge predicate on the "sender" edge.
func HasSender() predicate.SupportMessage {
	return predicate.SupportMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SenderTable, SenderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSenderWith applies the HasEdge predicate on the "sender" edge with a given conditions (other predicates).
func HasSenderWith(preds ...predicate.User) predicate.SupportMessage {
	return predicate.SupportMessage(func(s *sql.Selector) {
		step := newSenderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportMessage) predicate.SupportMessage {
	return predicate.SupportMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportMessage) predicate.SupportMessage {
	return predicate.SupportMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportMessage) predicate.SupportMessage {
	return predicate.SupportMessage(sql.NotPredicates(p))
}
