<template>
  <UserWorkspaceLayout>
    <main class="community-page store-page">
      <header class="community-head"><div><p class="community-eyebrow">DIGITAL GOODS</p><h1>自助发卡商城</h1><p>浏览可售卡密商品，支持余额、积分或已启用的平台支付方式购买，支付完成后自动交付。</p></div><button class="community-btn community-btn--quiet" @click="showOrders=!showOrders"><Icon name="document" size="sm" />{{showOrders?'返回商城':'购买记录'}}</button></header>
      <section class="marketplace-stats store-stats"><div><span>商品数</span><strong>{{products.length}}</strong></div><div><span>可售库存</span><strong>{{totalStock}}</strong></div><div><span>账户余额</span><strong>¥{{money(wallet.balance)}}</strong></div><div><span>积分</span><strong>{{money(wallet.points)}}</strong></div></section>
      <div v-if="!showOrders" class="store-toolbar"><div class="community-segmented"><button v-for="entry in categories" :key="entry" :class="{active:category===entry}" @click="category=entry">{{entry||'全部'}}</button></div><label class="community-search"><Icon name="search" size="sm"/><input v-model="search" placeholder="搜索商品" /></label></div>
      <section v-if="!showOrders&&filtered.length" class="store-grid"><article v-for="product in filtered" :key="product.id" class="store-product"><header><span class="community-chip community-chip--yellow">{{product.category}}</span><span v-if="requiresStock(product)" :class="['store-stock',{empty:product.stock<1}]">库存 {{product.stock}}</span><span v-else class="store-stock">{{fulfillmentText(product.fulfillment_type)}}</span></header><div><h2>{{product.name}}</h2><p>{{product.description||'暂无商品描述'}}</p></div><div v-if="product.fulfillment_type==='entitlement'" class="store-entitlement"><span>每件到账负载额度</span><strong>+{{product.fulfillment_value}}</strong></div><div class="store-prices"><strong>¥{{money(product.price)}}</strong><span v-if="product.points_price!=null">或 {{money(product.points_price)}} 积分</span></div><footer><span>{{fulfillmentText(product.fulfillment_type)}}</span><button class="community-btn" :disabled="requiresStock(product)&&product.stock<1" @click="openCheckout(product)">{{requiresStock(product)&&product.stock<1?'已售罄':'购买'}}</button></footer></article></section>
      <div v-if="!showOrders&&filtered.length===0" class="community-empty"><strong>暂无在售商品</strong><span>可以切换分类或稍后再来。</span></div>
      <div v-if="showOrders" class="community-table-wrap"><table class="community-table"><thead><tr><th>订单</th><th>商品</th><th>数量</th><th>支付</th><th>金额</th><th>状态</th><th>交付内容</th><th>时间</th></tr></thead><tbody><tr v-if="orders.length===0"><td colspan="8"><div class="community-empty compact">暂无购买记录</div></td></tr><tr v-for="order in orders" v-else :key="order.id"><td>{{order.order_no}}</td><td>{{order.product_name}}</td><td>{{order.quantity}}</td><td>{{order.payment_source==='points'?'积分':order.payment_source==='platform'?'平台支付':'余额'}}</td><td>{{order.payment_source==='points'?'': '¥'}}{{money(order.total_amount)}}</td><td><span class="community-status" :class="`community-status--${order.status}`">{{order.status}}</span></td><td><code>{{Array.isArray(order.delivery)?order.delivery.join(' · '):order.delivery}}</code></td><td>{{format(order.created_at)}}</td></tr></tbody></table></div>
      <div v-if="checkout" class="community-modal-backdrop" @click.self="checkout=null"><section class="community-modal" role="dialog" aria-modal="true" aria-label="确认购买"><header><div><p class="community-eyebrow">CHECKOUT</p><h2>{{checkout.name}}</h2><p>确认商品与支付方式</p></div><button class="community-icon-btn" title="关闭" @click="checkout=null"><Icon name="x" size="sm"/></button></header><form @submit.prevent="buy"><label>购买数量<input v-model.number="quantity" class="community-input" type="number" min="1" :max="requiresStock(checkout)?Math.max(1,checkout.stock):100" /></label><div class="store-order-summary"><div><span>单价</span><strong>¥{{money(checkout.price)}}</strong></div><div><span>合计</span><strong>¥{{money(checkout.price*quantity)}}</strong></div><div><span>当前余额</span><strong>¥{{money(wallet.balance)}}</strong></div></div><fieldset class="community-fieldset"><legend>支付方式</legend><label class="store-pay-option" :class="{disabled:wallet.balance<checkout.price*quantity}"><input v-model="paymentSource" type="radio" value="balance" :disabled="wallet.balance<checkout.price*quantity"/><span><strong>余额支付</strong><small>{{wallet.balance<checkout.price*quantity?'余额不足':`可用 ¥${money(wallet.balance)}`}}</small></span><b>¥{{money(checkout.price*quantity)}}</b></label><label v-if="checkout.points_price!=null" class="store-pay-option" :class="{disabled:wallet.points<(checkout.points_price||0)*quantity}"><input v-model="paymentSource" type="radio" value="points" :disabled="wallet.points<(checkout.points_price||0)*quantity"/><span><strong>积分支付</strong><small>{{wallet.points<(checkout.points_price||0)*quantity?'积分不足':`可用 ${money(wallet.points)} 积分`}}</small></span><b>{{money((checkout.points_price||0)*quantity)}} 积分</b></label><label v-for="method in platformMethods" :key="method" class="store-pay-option"><input type="radio" name="platform-method" :checked="paymentSource==='platform'&&platformMethod===method" @change="paymentSource='platform';platformMethod=method"/><span><strong>{{paymentMethodLabel(method)}}</strong><small>支付成功后自动交付</small></span><b>¥{{money(checkout.price*quantity)}}</b></label></fieldset><div class="store-checkout-total"><span>本次支付</span><strong>{{paymentSource==='points'?'':'¥'}}{{money(currentTotal)}} {{paymentSource==='points'?'积分':''}}</strong></div><footer><button type="button" class="community-btn community-btn--quiet" @click="checkout=null">取消</button><button class="community-btn" :disabled="buying||!canAfford||paymentSource==='platform'&&!platformMethod">{{buying?(paymentSource==='platform'?'创建支付中...':'交付中...'):'确认购买'}}</button></footer></form></section></div>
      <div v-if="pendingPayment" class="community-modal-backdrop"><section class="community-modal"><header><div><h2>订单待支付</h2><p>支付成功后系统会自动交付商品。</p></div><button class="community-icon-btn" title="关闭" @click="pendingPayment=null"><Icon name="x" size="sm"/></button></header><div class="platform-payment-state"><span>支付订单 #{{pendingPayment.order_id}}</span><strong>¥{{money(pendingPayment.pay_amount)}}</strong><small>请在 {{format(pendingPayment.expires_at)}} 前完成支付</small><img v-if="pendingPayment.qr_code&&pendingPayment.qr_code.startsWith('data:image')" :src="pendingPayment.qr_code" alt="支付二维码"/><code v-else-if="pendingPayment.qr_code">{{pendingPayment.qr_code}}</code></div><footer><button class="community-btn community-btn--quiet" @click="pendingPayment=null;showOrders=true;load()">查看购买记录</button><button v-if="pendingPayment.pay_url" class="community-btn" @click="openPaymentURL(pendingPayment.pay_url)">打开支付页面</button></footer></section></div>
    </main>
  </UserWorkspaceLayout>
</template>
<script setup lang="ts">
import{computed,onMounted,ref}from'vue'
import UserWorkspaceLayout from '@/components/layout/UserWorkspaceLayout.vue'
import Icon from '@/components/icons/Icon.vue'
import{communityAPI,type StoreOrder,type StoreProduct,type StoreWallet}from'@/api/community'
import{paymentAPI}from'@/api/payment'
import type{CreateOrderResult,PaymentType}from'@/types/payment'
import{useAppStore}from'@/stores/app'
const app=useAppStore(),products=ref<StoreProduct[]>([]),orders=ref<StoreOrder[]>([]),wallet=ref<StoreWallet>({balance:0,points:0}),category=ref(''),search=ref(''),showOrders=ref(false),checkout=ref<StoreProduct|null>(null),quantity=ref(1),paymentSource=ref<'balance'|'points'|'platform'>('balance'),platformMethod=ref<PaymentType|''>(''),platformMethods=ref<PaymentType[]>([]),pendingPayment=ref<CreateOrderResult|null>(null),buying=ref(false)
const categories=computed(()=>['',...new Set(products.value.map(product=>product.category))])
const filtered=computed(()=>products.value.filter(product=>(!category.value||product.category===category.value)&&(!search.value||`${product.name} ${product.description}`.toLowerCase().includes(search.value.toLowerCase()))))
const totalStock=computed(()=>products.value.reduce((sum,product)=>sum+product.stock,0))
const currentTotal=computed(()=>checkout.value?(paymentSource.value==='points'?(checkout.value.points_price||0):checkout.value.price)*quantity.value:0)
const canAfford=computed(()=>paymentSource.value==='platform'||(paymentSource.value==='points'?wallet.value.points>=currentTotal.value:wallet.value.balance>=currentTotal.value))
const money=(value:number)=>Number(value||0).toFixed(2)
const format=(value:string)=>new Date(value).toLocaleString('zh-CN')
const requiresStock=(product:StoreProduct)=>['card','redeem_code'].includes(product.fulfillment_type)
const fulfillmentText=(type:string)=>({card:'卡密自动交付',redeem_code:'兑换码自动交付',balance:'余额自动到账',entitlement:'负载额度自动到账'} as Record<string,string>)[type]||'自动交付'
const paymentMethodLabel=(value:string)=>({alipay:'支付宝',alipay_direct:'支付宝',wxpay:'微信支付',wxpay_direct:'微信支付',stripe:'Stripe',easypay:'易支付',airwallex:'Airwallex'}as Record<string,string>)[value]||value
async function load(){try{const [nextProducts,nextOrders,nextWallet,paymentConfig]=await Promise.all([communityAPI.products(),communityAPI.storeOrders(),communityAPI.storeWallet(),paymentAPI.getConfig().catch(()=>null)]);products.value=nextProducts;orders.value=nextOrders;wallet.value=nextWallet;platformMethods.value=paymentConfig?.data.payment_enabled?paymentConfig.data.enabled_payment_types:[]}catch{app.showError('商城加载失败')}}
function openCheckout(product:StoreProduct){checkout.value=product;quantity.value=1;paymentSource.value='balance';platformMethod.value=platformMethods.value[0]||''}
function openPaymentURL(url:string){const opened=window.open(url,'paymentPopup','width=520,height=720');if(!opened)window.location.href=url}
function launchPlatformPayment(result:CreateOrderResult){pendingPayment.value=result;if(result.client_secret){const path=result.payment_type==='airwallex'?'/payment/airwallex':'/payment/stripe';const query=new URLSearchParams({order_id:String(result.order_id),...(result.client_secret?{client_secret:result.client_secret}:{}),...(result.out_trade_no?{out_trade_no:result.out_trade_no}:{})});openPaymentURL(`${path}?${query}`)}else if(result.pay_url)openPaymentURL(result.pay_url)}
async function buy(){if(!checkout.value||!canAfford.value)return;buying.value=true;try{if(paymentSource.value==='platform'){const created=await communityAPI.createPlatformStoreOrder(checkout.value.id,{quantity:quantity.value,payment_type:platformMethod.value,return_url:`${window.location.origin}/store`});checkout.value=null;launchPlatformPayment(created.payment);return}const order=await communityAPI.buy(checkout.value.id,quantity.value,paymentSource.value);orders.value.unshift(order);checkout.value=null;await load();app.showSuccess('购买成功，商品已自动交付')}catch{app.showError('购买失败，请检查支付方式、余额或库存')}finally{buying.value=false}}
onMounted(load)
</script>
<style src="@/styles/community.css"></style>
<style scoped>.store-entitlement{display:flex;align-items:center;justify-content:space-between;border:1px solid var(--line);padding:9px}.store-entitlement span{color:var(--muted);font-size:.7rem}.store-entitlement strong{font-size:1rem}.store-order-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border:1px solid var(--line)}.store-order-summary>div{display:grid;gap:4px;padding:10px;border-right:1px solid var(--line)}.store-order-summary>div:last-child{border-right:0}.store-order-summary span{color:var(--muted);font-size:.68rem}.store-pay-option.disabled{cursor:not-allowed;opacity:.55}.platform-payment-state{display:grid;place-items:center;gap:9px;border:1px solid var(--line);padding:22px;text-align:center}.platform-payment-state>strong{font-size:1.45rem}.platform-payment-state>small{color:var(--muted)}.platform-payment-state img{width:min(240px,100%);aspect-ratio:1;object-fit:contain}.platform-payment-state code{max-width:100%;overflow-wrap:anywhere;white-space:pre-wrap}@media(max-width:560px){.store-order-summary{grid-template-columns:1fr}.store-order-summary>div{border-right:0;border-bottom:1px solid var(--line)}.store-order-summary>div:last-child{border-bottom:0}}</style>
